// output_buf.v

// Generated using ACDS version 20.1 720

`timescale 1 ps / 1 ps
module output_buf (
		input  wire [0:0] din,       //       din.export
		output wire [0:0] pad_out,   //   pad_out.export
		output wire [0:0] pad_out_b  // pad_out_b.export
	);

	output_buf_altera_gpio_201_5h2tshy gpio_0 (
		.din       (din),       //       din.export
		.pad_out   (pad_out),   //   pad_out.export
		.pad_out_b (pad_out_b)  // pad_out_b.export
	);

endmodule
