// peripheral_sys_sysid_qsys_0.v

// Generated using ACDS version 23.4 79

`timescale 1 ps / 1 ps
module peripheral_sys_sysid_qsys_0 (
		input  wire        clock,    //           clk.clk
		input  wire        reset_n,  //         reset.reset_n
		output wire [31:0] readdata, // control_slave.readdata
		input  wire        address   //              .address
	);

	altera_avalon_sysid_qsys #(
		.ID_VALUE  (-559038737),
		.TIMESTAMP (0)
	) sysid_qsys_0 (
		.clock    (clock),    //   input,   width = 1,           clk.clk
		.reset_n  (reset_n),  //   input,   width = 1,         reset.reset_n
		.readdata (readdata), //  output,  width = 32, control_slave.readdata
		.address  (address)   //   input,   width = 1,              .address
	);

endmodule
