// clk_buf.v

// Generated using ACDS version 20.1 720

`timescale 1 ps / 1 ps
module clk_buf (
		output wire [0:0] dout,   //   dout.export
		input  wire [0:0] pad_in  // pad_in.export
	);

	clk_buf_altera_gpio_201_ordjpnq gpio_0 (
		.dout   (dout),   //   dout.export
		.pad_in (pad_in)  // pad_in.export
	);

endmodule
