// system_bd_mm_interconnect_2.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module system_bd_mm_interconnect_2 (
		input  wire [0:0]  hdmi_dmac_0_m_src_axi_awid,                                           //                                          hdmi_dmac_0_m_src_axi.awid
		input  wire [31:0] hdmi_dmac_0_m_src_axi_awaddr,                                         //                                                               .awaddr
		input  wire [3:0]  hdmi_dmac_0_m_src_axi_awlen,                                          //                                                               .awlen
		input  wire [2:0]  hdmi_dmac_0_m_src_axi_awsize,                                         //                                                               .awsize
		input  wire [1:0]  hdmi_dmac_0_m_src_axi_awburst,                                        //                                                               .awburst
		input  wire [1:0]  hdmi_dmac_0_m_src_axi_awlock,                                         //                                                               .awlock
		input  wire [3:0]  hdmi_dmac_0_m_src_axi_awcache,                                        //                                                               .awcache
		input  wire [2:0]  hdmi_dmac_0_m_src_axi_awprot,                                         //                                                               .awprot
		input  wire        hdmi_dmac_0_m_src_axi_awvalid,                                        //                                                               .awvalid
		output wire        hdmi_dmac_0_m_src_axi_awready,                                        //                                                               .awready
		input  wire [0:0]  hdmi_dmac_0_m_src_axi_wid,                                            //                                                               .wid
		input  wire [63:0] hdmi_dmac_0_m_src_axi_wdata,                                          //                                                               .wdata
		input  wire [7:0]  hdmi_dmac_0_m_src_axi_wstrb,                                          //                                                               .wstrb
		input  wire        hdmi_dmac_0_m_src_axi_wlast,                                          //                                                               .wlast
		input  wire        hdmi_dmac_0_m_src_axi_wvalid,                                         //                                                               .wvalid
		output wire        hdmi_dmac_0_m_src_axi_wready,                                         //                                                               .wready
		output wire [0:0]  hdmi_dmac_0_m_src_axi_bid,                                            //                                                               .bid
		output wire [1:0]  hdmi_dmac_0_m_src_axi_bresp,                                          //                                                               .bresp
		output wire        hdmi_dmac_0_m_src_axi_bvalid,                                         //                                                               .bvalid
		input  wire        hdmi_dmac_0_m_src_axi_bready,                                         //                                                               .bready
		input  wire [0:0]  hdmi_dmac_0_m_src_axi_arid,                                           //                                                               .arid
		input  wire [31:0] hdmi_dmac_0_m_src_axi_araddr,                                         //                                                               .araddr
		input  wire [3:0]  hdmi_dmac_0_m_src_axi_arlen,                                          //                                                               .arlen
		input  wire [2:0]  hdmi_dmac_0_m_src_axi_arsize,                                         //                                                               .arsize
		input  wire [1:0]  hdmi_dmac_0_m_src_axi_arburst,                                        //                                                               .arburst
		input  wire [1:0]  hdmi_dmac_0_m_src_axi_arlock,                                         //                                                               .arlock
		input  wire [3:0]  hdmi_dmac_0_m_src_axi_arcache,                                        //                                                               .arcache
		input  wire [2:0]  hdmi_dmac_0_m_src_axi_arprot,                                         //                                                               .arprot
		input  wire        hdmi_dmac_0_m_src_axi_arvalid,                                        //                                                               .arvalid
		output wire        hdmi_dmac_0_m_src_axi_arready,                                        //                                                               .arready
		output wire [0:0]  hdmi_dmac_0_m_src_axi_rid,                                            //                                                               .rid
		output wire [63:0] hdmi_dmac_0_m_src_axi_rdata,                                          //                                                               .rdata
		output wire [1:0]  hdmi_dmac_0_m_src_axi_rresp,                                          //                                                               .rresp
		output wire        hdmi_dmac_0_m_src_axi_rlast,                                          //                                                               .rlast
		output wire        hdmi_dmac_0_m_src_axi_rvalid,                                         //                                                               .rvalid
		input  wire        hdmi_dmac_0_m_src_axi_rready,                                         //                                                               .rready
		input  wire        sys_hps_h2f_user1_clock_clk,                                          //                                        sys_hps_h2f_user1_clock.clk
		input  wire        hdmi_dmac_0_m_src_axi_reset_reset_bridge_in_reset_reset,              //              hdmi_dmac_0_m_src_axi_reset_reset_bridge_in_reset.reset
		input  wire        sys_hps_f2h_sdram0_data_translator_reset_reset_bridge_in_reset_reset, // sys_hps_f2h_sdram0_data_translator_reset_reset_bridge_in_reset.reset
		output wire [28:0] sys_hps_f2h_sdram0_data_address,                                      //                                        sys_hps_f2h_sdram0_data.address
		output wire        sys_hps_f2h_sdram0_data_write,                                        //                                                               .write
		output wire        sys_hps_f2h_sdram0_data_read,                                         //                                                               .read
		input  wire [63:0] sys_hps_f2h_sdram0_data_readdata,                                     //                                                               .readdata
		output wire [63:0] sys_hps_f2h_sdram0_data_writedata,                                    //                                                               .writedata
		output wire [7:0]  sys_hps_f2h_sdram0_data_burstcount,                                   //                                                               .burstcount
		output wire [7:0]  sys_hps_f2h_sdram0_data_byteenable,                                   //                                                               .byteenable
		input  wire        sys_hps_f2h_sdram0_data_readdatavalid,                                //                                                               .readdatavalid
		input  wire        sys_hps_f2h_sdram0_data_waitrequest                                   //                                                               .waitrequest
	);

	wire          rsp_mux_src_valid;                                           // rsp_mux:src_valid -> hdmi_dmac_0_m_src_axi_agent:write_rp_valid
	wire  [152:0] rsp_mux_src_data;                                            // rsp_mux:src_data -> hdmi_dmac_0_m_src_axi_agent:write_rp_data
	wire          rsp_mux_src_ready;                                           // hdmi_dmac_0_m_src_axi_agent:write_rp_ready -> rsp_mux:src_ready
	wire    [1:0] rsp_mux_src_channel;                                         // rsp_mux:src_channel -> hdmi_dmac_0_m_src_axi_agent:write_rp_channel
	wire          rsp_mux_src_startofpacket;                                   // rsp_mux:src_startofpacket -> hdmi_dmac_0_m_src_axi_agent:write_rp_startofpacket
	wire          rsp_mux_src_endofpacket;                                     // rsp_mux:src_endofpacket -> hdmi_dmac_0_m_src_axi_agent:write_rp_endofpacket
	wire          rsp_mux_001_src_valid;                                       // rsp_mux_001:src_valid -> hdmi_dmac_0_m_src_axi_agent:read_rp_valid
	wire  [152:0] rsp_mux_001_src_data;                                        // rsp_mux_001:src_data -> hdmi_dmac_0_m_src_axi_agent:read_rp_data
	wire          rsp_mux_001_src_ready;                                       // hdmi_dmac_0_m_src_axi_agent:read_rp_ready -> rsp_mux_001:src_ready
	wire    [1:0] rsp_mux_001_src_channel;                                     // rsp_mux_001:src_channel -> hdmi_dmac_0_m_src_axi_agent:read_rp_channel
	wire          rsp_mux_001_src_startofpacket;                               // rsp_mux_001:src_startofpacket -> hdmi_dmac_0_m_src_axi_agent:read_rp_startofpacket
	wire          rsp_mux_001_src_endofpacket;                                 // rsp_mux_001:src_endofpacket -> hdmi_dmac_0_m_src_axi_agent:read_rp_endofpacket
	wire   [63:0] sys_hps_f2h_sdram0_data_agent_m0_readdata;                   // sys_hps_f2h_sdram0_data_translator:uav_readdata -> sys_hps_f2h_sdram0_data_agent:m0_readdata
	wire          sys_hps_f2h_sdram0_data_agent_m0_waitrequest;                // sys_hps_f2h_sdram0_data_translator:uav_waitrequest -> sys_hps_f2h_sdram0_data_agent:m0_waitrequest
	wire          sys_hps_f2h_sdram0_data_agent_m0_debugaccess;                // sys_hps_f2h_sdram0_data_agent:m0_debugaccess -> sys_hps_f2h_sdram0_data_translator:uav_debugaccess
	wire   [31:0] sys_hps_f2h_sdram0_data_agent_m0_address;                    // sys_hps_f2h_sdram0_data_agent:m0_address -> sys_hps_f2h_sdram0_data_translator:uav_address
	wire    [7:0] sys_hps_f2h_sdram0_data_agent_m0_byteenable;                 // sys_hps_f2h_sdram0_data_agent:m0_byteenable -> sys_hps_f2h_sdram0_data_translator:uav_byteenable
	wire          sys_hps_f2h_sdram0_data_agent_m0_read;                       // sys_hps_f2h_sdram0_data_agent:m0_read -> sys_hps_f2h_sdram0_data_translator:uav_read
	wire          sys_hps_f2h_sdram0_data_agent_m0_readdatavalid;              // sys_hps_f2h_sdram0_data_translator:uav_readdatavalid -> sys_hps_f2h_sdram0_data_agent:m0_readdatavalid
	wire          sys_hps_f2h_sdram0_data_agent_m0_lock;                       // sys_hps_f2h_sdram0_data_agent:m0_lock -> sys_hps_f2h_sdram0_data_translator:uav_lock
	wire   [63:0] sys_hps_f2h_sdram0_data_agent_m0_writedata;                  // sys_hps_f2h_sdram0_data_agent:m0_writedata -> sys_hps_f2h_sdram0_data_translator:uav_writedata
	wire          sys_hps_f2h_sdram0_data_agent_m0_write;                      // sys_hps_f2h_sdram0_data_agent:m0_write -> sys_hps_f2h_sdram0_data_translator:uav_write
	wire   [10:0] sys_hps_f2h_sdram0_data_agent_m0_burstcount;                 // sys_hps_f2h_sdram0_data_agent:m0_burstcount -> sys_hps_f2h_sdram0_data_translator:uav_burstcount
	wire          sys_hps_f2h_sdram0_data_agent_rf_source_valid;               // sys_hps_f2h_sdram0_data_agent:rf_source_valid -> sys_hps_f2h_sdram0_data_agent_rsp_fifo:in_valid
	wire  [153:0] sys_hps_f2h_sdram0_data_agent_rf_source_data;                // sys_hps_f2h_sdram0_data_agent:rf_source_data -> sys_hps_f2h_sdram0_data_agent_rsp_fifo:in_data
	wire          sys_hps_f2h_sdram0_data_agent_rf_source_ready;               // sys_hps_f2h_sdram0_data_agent_rsp_fifo:in_ready -> sys_hps_f2h_sdram0_data_agent:rf_source_ready
	wire          sys_hps_f2h_sdram0_data_agent_rf_source_startofpacket;       // sys_hps_f2h_sdram0_data_agent:rf_source_startofpacket -> sys_hps_f2h_sdram0_data_agent_rsp_fifo:in_startofpacket
	wire          sys_hps_f2h_sdram0_data_agent_rf_source_endofpacket;         // sys_hps_f2h_sdram0_data_agent:rf_source_endofpacket -> sys_hps_f2h_sdram0_data_agent_rsp_fifo:in_endofpacket
	wire          sys_hps_f2h_sdram0_data_agent_rsp_fifo_out_valid;            // sys_hps_f2h_sdram0_data_agent_rsp_fifo:out_valid -> sys_hps_f2h_sdram0_data_agent:rf_sink_valid
	wire  [153:0] sys_hps_f2h_sdram0_data_agent_rsp_fifo_out_data;             // sys_hps_f2h_sdram0_data_agent_rsp_fifo:out_data -> sys_hps_f2h_sdram0_data_agent:rf_sink_data
	wire          sys_hps_f2h_sdram0_data_agent_rsp_fifo_out_ready;            // sys_hps_f2h_sdram0_data_agent:rf_sink_ready -> sys_hps_f2h_sdram0_data_agent_rsp_fifo:out_ready
	wire          sys_hps_f2h_sdram0_data_agent_rsp_fifo_out_startofpacket;    // sys_hps_f2h_sdram0_data_agent_rsp_fifo:out_startofpacket -> sys_hps_f2h_sdram0_data_agent:rf_sink_startofpacket
	wire          sys_hps_f2h_sdram0_data_agent_rsp_fifo_out_endofpacket;      // sys_hps_f2h_sdram0_data_agent_rsp_fifo:out_endofpacket -> sys_hps_f2h_sdram0_data_agent:rf_sink_endofpacket
	wire          sys_hps_f2h_sdram0_data_agent_rdata_fifo_src_valid;          // sys_hps_f2h_sdram0_data_agent:rdata_fifo_src_valid -> sys_hps_f2h_sdram0_data_agent_rdata_fifo:in_valid
	wire   [65:0] sys_hps_f2h_sdram0_data_agent_rdata_fifo_src_data;           // sys_hps_f2h_sdram0_data_agent:rdata_fifo_src_data -> sys_hps_f2h_sdram0_data_agent_rdata_fifo:in_data
	wire          sys_hps_f2h_sdram0_data_agent_rdata_fifo_src_ready;          // sys_hps_f2h_sdram0_data_agent_rdata_fifo:in_ready -> sys_hps_f2h_sdram0_data_agent:rdata_fifo_src_ready
	wire          hdmi_dmac_0_m_src_axi_agent_write_cp_valid;                  // hdmi_dmac_0_m_src_axi_agent:write_cp_valid -> router:sink_valid
	wire  [152:0] hdmi_dmac_0_m_src_axi_agent_write_cp_data;                   // hdmi_dmac_0_m_src_axi_agent:write_cp_data -> router:sink_data
	wire          hdmi_dmac_0_m_src_axi_agent_write_cp_ready;                  // router:sink_ready -> hdmi_dmac_0_m_src_axi_agent:write_cp_ready
	wire          hdmi_dmac_0_m_src_axi_agent_write_cp_startofpacket;          // hdmi_dmac_0_m_src_axi_agent:write_cp_startofpacket -> router:sink_startofpacket
	wire          hdmi_dmac_0_m_src_axi_agent_write_cp_endofpacket;            // hdmi_dmac_0_m_src_axi_agent:write_cp_endofpacket -> router:sink_endofpacket
	wire          router_src_valid;                                            // router:src_valid -> cmd_demux:sink_valid
	wire  [152:0] router_src_data;                                             // router:src_data -> cmd_demux:sink_data
	wire          router_src_ready;                                            // cmd_demux:sink_ready -> router:src_ready
	wire    [1:0] router_src_channel;                                          // router:src_channel -> cmd_demux:sink_channel
	wire          router_src_startofpacket;                                    // router:src_startofpacket -> cmd_demux:sink_startofpacket
	wire          router_src_endofpacket;                                      // router:src_endofpacket -> cmd_demux:sink_endofpacket
	wire          hdmi_dmac_0_m_src_axi_agent_read_cp_valid;                   // hdmi_dmac_0_m_src_axi_agent:read_cp_valid -> router_001:sink_valid
	wire  [152:0] hdmi_dmac_0_m_src_axi_agent_read_cp_data;                    // hdmi_dmac_0_m_src_axi_agent:read_cp_data -> router_001:sink_data
	wire          hdmi_dmac_0_m_src_axi_agent_read_cp_ready;                   // router_001:sink_ready -> hdmi_dmac_0_m_src_axi_agent:read_cp_ready
	wire          hdmi_dmac_0_m_src_axi_agent_read_cp_startofpacket;           // hdmi_dmac_0_m_src_axi_agent:read_cp_startofpacket -> router_001:sink_startofpacket
	wire          hdmi_dmac_0_m_src_axi_agent_read_cp_endofpacket;             // hdmi_dmac_0_m_src_axi_agent:read_cp_endofpacket -> router_001:sink_endofpacket
	wire          router_001_src_valid;                                        // router_001:src_valid -> cmd_demux_001:sink_valid
	wire  [152:0] router_001_src_data;                                         // router_001:src_data -> cmd_demux_001:sink_data
	wire          router_001_src_ready;                                        // cmd_demux_001:sink_ready -> router_001:src_ready
	wire    [1:0] router_001_src_channel;                                      // router_001:src_channel -> cmd_demux_001:sink_channel
	wire          router_001_src_startofpacket;                                // router_001:src_startofpacket -> cmd_demux_001:sink_startofpacket
	wire          router_001_src_endofpacket;                                  // router_001:src_endofpacket -> cmd_demux_001:sink_endofpacket
	wire          router_002_src_valid;                                        // router_002:src_valid -> rsp_demux:sink_valid
	wire  [152:0] router_002_src_data;                                         // router_002:src_data -> rsp_demux:sink_data
	wire          router_002_src_ready;                                        // rsp_demux:sink_ready -> router_002:src_ready
	wire    [1:0] router_002_src_channel;                                      // router_002:src_channel -> rsp_demux:sink_channel
	wire          router_002_src_startofpacket;                                // router_002:src_startofpacket -> rsp_demux:sink_startofpacket
	wire          router_002_src_endofpacket;                                  // router_002:src_endofpacket -> rsp_demux:sink_endofpacket
	wire          cmd_mux_src_valid;                                           // cmd_mux:src_valid -> sys_hps_f2h_sdram0_data_burst_adapter:sink0_valid
	wire  [152:0] cmd_mux_src_data;                                            // cmd_mux:src_data -> sys_hps_f2h_sdram0_data_burst_adapter:sink0_data
	wire          cmd_mux_src_ready;                                           // sys_hps_f2h_sdram0_data_burst_adapter:sink0_ready -> cmd_mux:src_ready
	wire    [1:0] cmd_mux_src_channel;                                         // cmd_mux:src_channel -> sys_hps_f2h_sdram0_data_burst_adapter:sink0_channel
	wire          cmd_mux_src_startofpacket;                                   // cmd_mux:src_startofpacket -> sys_hps_f2h_sdram0_data_burst_adapter:sink0_startofpacket
	wire          cmd_mux_src_endofpacket;                                     // cmd_mux:src_endofpacket -> sys_hps_f2h_sdram0_data_burst_adapter:sink0_endofpacket
	wire          sys_hps_f2h_sdram0_data_burst_adapter_source0_valid;         // sys_hps_f2h_sdram0_data_burst_adapter:source0_valid -> agent_pipeline:in_valid
	wire  [152:0] sys_hps_f2h_sdram0_data_burst_adapter_source0_data;          // sys_hps_f2h_sdram0_data_burst_adapter:source0_data -> agent_pipeline:in_data
	wire          sys_hps_f2h_sdram0_data_burst_adapter_source0_ready;         // agent_pipeline:in_ready -> sys_hps_f2h_sdram0_data_burst_adapter:source0_ready
	wire    [1:0] sys_hps_f2h_sdram0_data_burst_adapter_source0_channel;       // sys_hps_f2h_sdram0_data_burst_adapter:source0_channel -> agent_pipeline:in_channel
	wire          sys_hps_f2h_sdram0_data_burst_adapter_source0_startofpacket; // sys_hps_f2h_sdram0_data_burst_adapter:source0_startofpacket -> agent_pipeline:in_startofpacket
	wire          sys_hps_f2h_sdram0_data_burst_adapter_source0_endofpacket;   // sys_hps_f2h_sdram0_data_burst_adapter:source0_endofpacket -> agent_pipeline:in_endofpacket
	wire          agent_pipeline_source0_valid;                                // agent_pipeline:out_valid -> sys_hps_f2h_sdram0_data_agent:cp_valid
	wire  [152:0] agent_pipeline_source0_data;                                 // agent_pipeline:out_data -> sys_hps_f2h_sdram0_data_agent:cp_data
	wire          agent_pipeline_source0_ready;                                // sys_hps_f2h_sdram0_data_agent:cp_ready -> agent_pipeline:out_ready
	wire    [1:0] agent_pipeline_source0_channel;                              // agent_pipeline:out_channel -> sys_hps_f2h_sdram0_data_agent:cp_channel
	wire          agent_pipeline_source0_startofpacket;                        // agent_pipeline:out_startofpacket -> sys_hps_f2h_sdram0_data_agent:cp_startofpacket
	wire          agent_pipeline_source0_endofpacket;                          // agent_pipeline:out_endofpacket -> sys_hps_f2h_sdram0_data_agent:cp_endofpacket
	wire          sys_hps_f2h_sdram0_data_agent_rp_valid;                      // sys_hps_f2h_sdram0_data_agent:rp_valid -> agent_pipeline_001:in_valid
	wire  [152:0] sys_hps_f2h_sdram0_data_agent_rp_data;                       // sys_hps_f2h_sdram0_data_agent:rp_data -> agent_pipeline_001:in_data
	wire          sys_hps_f2h_sdram0_data_agent_rp_ready;                      // agent_pipeline_001:in_ready -> sys_hps_f2h_sdram0_data_agent:rp_ready
	wire          sys_hps_f2h_sdram0_data_agent_rp_startofpacket;              // sys_hps_f2h_sdram0_data_agent:rp_startofpacket -> agent_pipeline_001:in_startofpacket
	wire          sys_hps_f2h_sdram0_data_agent_rp_endofpacket;                // sys_hps_f2h_sdram0_data_agent:rp_endofpacket -> agent_pipeline_001:in_endofpacket
	wire          agent_pipeline_001_source0_valid;                            // agent_pipeline_001:out_valid -> router_002:sink_valid
	wire  [152:0] agent_pipeline_001_source0_data;                             // agent_pipeline_001:out_data -> router_002:sink_data
	wire          agent_pipeline_001_source0_ready;                            // router_002:sink_ready -> agent_pipeline_001:out_ready
	wire          agent_pipeline_001_source0_startofpacket;                    // agent_pipeline_001:out_startofpacket -> router_002:sink_startofpacket
	wire          agent_pipeline_001_source0_endofpacket;                      // agent_pipeline_001:out_endofpacket -> router_002:sink_endofpacket
	wire          cmd_demux_src0_valid;                                        // cmd_demux:src0_valid -> mux_pipeline:in_valid
	wire  [152:0] cmd_demux_src0_data;                                         // cmd_demux:src0_data -> mux_pipeline:in_data
	wire          cmd_demux_src0_ready;                                        // mux_pipeline:in_ready -> cmd_demux:src0_ready
	wire    [1:0] cmd_demux_src0_channel;                                      // cmd_demux:src0_channel -> mux_pipeline:in_channel
	wire          cmd_demux_src0_startofpacket;                                // cmd_demux:src0_startofpacket -> mux_pipeline:in_startofpacket
	wire          cmd_demux_src0_endofpacket;                                  // cmd_demux:src0_endofpacket -> mux_pipeline:in_endofpacket
	wire          mux_pipeline_source0_valid;                                  // mux_pipeline:out_valid -> cmd_mux:sink0_valid
	wire  [152:0] mux_pipeline_source0_data;                                   // mux_pipeline:out_data -> cmd_mux:sink0_data
	wire          mux_pipeline_source0_ready;                                  // cmd_mux:sink0_ready -> mux_pipeline:out_ready
	wire    [1:0] mux_pipeline_source0_channel;                                // mux_pipeline:out_channel -> cmd_mux:sink0_channel
	wire          mux_pipeline_source0_startofpacket;                          // mux_pipeline:out_startofpacket -> cmd_mux:sink0_startofpacket
	wire          mux_pipeline_source0_endofpacket;                            // mux_pipeline:out_endofpacket -> cmd_mux:sink0_endofpacket
	wire          cmd_demux_001_src0_valid;                                    // cmd_demux_001:src0_valid -> mux_pipeline_001:in_valid
	wire  [152:0] cmd_demux_001_src0_data;                                     // cmd_demux_001:src0_data -> mux_pipeline_001:in_data
	wire          cmd_demux_001_src0_ready;                                    // mux_pipeline_001:in_ready -> cmd_demux_001:src0_ready
	wire    [1:0] cmd_demux_001_src0_channel;                                  // cmd_demux_001:src0_channel -> mux_pipeline_001:in_channel
	wire          cmd_demux_001_src0_startofpacket;                            // cmd_demux_001:src0_startofpacket -> mux_pipeline_001:in_startofpacket
	wire          cmd_demux_001_src0_endofpacket;                              // cmd_demux_001:src0_endofpacket -> mux_pipeline_001:in_endofpacket
	wire          mux_pipeline_001_source0_valid;                              // mux_pipeline_001:out_valid -> cmd_mux:sink1_valid
	wire  [152:0] mux_pipeline_001_source0_data;                               // mux_pipeline_001:out_data -> cmd_mux:sink1_data
	wire          mux_pipeline_001_source0_ready;                              // cmd_mux:sink1_ready -> mux_pipeline_001:out_ready
	wire    [1:0] mux_pipeline_001_source0_channel;                            // mux_pipeline_001:out_channel -> cmd_mux:sink1_channel
	wire          mux_pipeline_001_source0_startofpacket;                      // mux_pipeline_001:out_startofpacket -> cmd_mux:sink1_startofpacket
	wire          mux_pipeline_001_source0_endofpacket;                        // mux_pipeline_001:out_endofpacket -> cmd_mux:sink1_endofpacket
	wire          rsp_demux_src0_valid;                                        // rsp_demux:src0_valid -> mux_pipeline_002:in_valid
	wire  [152:0] rsp_demux_src0_data;                                         // rsp_demux:src0_data -> mux_pipeline_002:in_data
	wire          rsp_demux_src0_ready;                                        // mux_pipeline_002:in_ready -> rsp_demux:src0_ready
	wire    [1:0] rsp_demux_src0_channel;                                      // rsp_demux:src0_channel -> mux_pipeline_002:in_channel
	wire          rsp_demux_src0_startofpacket;                                // rsp_demux:src0_startofpacket -> mux_pipeline_002:in_startofpacket
	wire          rsp_demux_src0_endofpacket;                                  // rsp_demux:src0_endofpacket -> mux_pipeline_002:in_endofpacket
	wire          mux_pipeline_002_source0_valid;                              // mux_pipeline_002:out_valid -> rsp_mux:sink0_valid
	wire  [152:0] mux_pipeline_002_source0_data;                               // mux_pipeline_002:out_data -> rsp_mux:sink0_data
	wire          mux_pipeline_002_source0_ready;                              // rsp_mux:sink0_ready -> mux_pipeline_002:out_ready
	wire    [1:0] mux_pipeline_002_source0_channel;                            // mux_pipeline_002:out_channel -> rsp_mux:sink0_channel
	wire          mux_pipeline_002_source0_startofpacket;                      // mux_pipeline_002:out_startofpacket -> rsp_mux:sink0_startofpacket
	wire          mux_pipeline_002_source0_endofpacket;                        // mux_pipeline_002:out_endofpacket -> rsp_mux:sink0_endofpacket
	wire          rsp_demux_src1_valid;                                        // rsp_demux:src1_valid -> mux_pipeline_003:in_valid
	wire  [152:0] rsp_demux_src1_data;                                         // rsp_demux:src1_data -> mux_pipeline_003:in_data
	wire          rsp_demux_src1_ready;                                        // mux_pipeline_003:in_ready -> rsp_demux:src1_ready
	wire    [1:0] rsp_demux_src1_channel;                                      // rsp_demux:src1_channel -> mux_pipeline_003:in_channel
	wire          rsp_demux_src1_startofpacket;                                // rsp_demux:src1_startofpacket -> mux_pipeline_003:in_startofpacket
	wire          rsp_demux_src1_endofpacket;                                  // rsp_demux:src1_endofpacket -> mux_pipeline_003:in_endofpacket
	wire          mux_pipeline_003_source0_valid;                              // mux_pipeline_003:out_valid -> rsp_mux_001:sink0_valid
	wire  [152:0] mux_pipeline_003_source0_data;                               // mux_pipeline_003:out_data -> rsp_mux_001:sink0_data
	wire          mux_pipeline_003_source0_ready;                              // rsp_mux_001:sink0_ready -> mux_pipeline_003:out_ready
	wire    [1:0] mux_pipeline_003_source0_channel;                            // mux_pipeline_003:out_channel -> rsp_mux_001:sink0_channel
	wire          mux_pipeline_003_source0_startofpacket;                      // mux_pipeline_003:out_startofpacket -> rsp_mux_001:sink0_startofpacket
	wire          mux_pipeline_003_source0_endofpacket;                        // mux_pipeline_003:out_endofpacket -> rsp_mux_001:sink0_endofpacket
	wire          sys_hps_f2h_sdram0_data_agent_rdata_fifo_out_valid;          // sys_hps_f2h_sdram0_data_agent_rdata_fifo:out_valid -> avalon_st_adapter:in_0_valid
	wire   [65:0] sys_hps_f2h_sdram0_data_agent_rdata_fifo_out_data;           // sys_hps_f2h_sdram0_data_agent_rdata_fifo:out_data -> avalon_st_adapter:in_0_data
	wire          sys_hps_f2h_sdram0_data_agent_rdata_fifo_out_ready;          // avalon_st_adapter:in_0_ready -> sys_hps_f2h_sdram0_data_agent_rdata_fifo:out_ready
	wire          avalon_st_adapter_out_0_valid;                               // avalon_st_adapter:out_0_valid -> sys_hps_f2h_sdram0_data_agent:rdata_fifo_sink_valid
	wire   [65:0] avalon_st_adapter_out_0_data;                                // avalon_st_adapter:out_0_data -> sys_hps_f2h_sdram0_data_agent:rdata_fifo_sink_data
	wire          avalon_st_adapter_out_0_ready;                               // sys_hps_f2h_sdram0_data_agent:rdata_fifo_sink_ready -> avalon_st_adapter:out_0_ready
	wire    [0:0] avalon_st_adapter_out_0_error;                               // avalon_st_adapter:out_0_error -> sys_hps_f2h_sdram0_data_agent:rdata_fifo_sink_error

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (29),
		.AV_DATA_W                      (64),
		.UAV_DATA_W                     (64),
		.AV_BURSTCOUNT_W                (8),
		.AV_BYTEENABLE_W                (8),
		.UAV_BYTEENABLE_W               (8),
		.UAV_ADDRESS_W                  (32),
		.UAV_BURSTCOUNT_W               (11),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (1),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (8),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (1),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) sys_hps_f2h_sdram0_data_translator (
		.clk                    (sys_hps_h2f_user1_clock_clk),                                          //                      clk.clk
		.reset                  (sys_hps_f2h_sdram0_data_translator_reset_reset_bridge_in_reset_reset), //                    reset.reset
		.uav_address            (sys_hps_f2h_sdram0_data_agent_m0_address),                             // avalon_universal_slave_0.address
		.uav_burstcount         (sys_hps_f2h_sdram0_data_agent_m0_burstcount),                          //                         .burstcount
		.uav_read               (sys_hps_f2h_sdram0_data_agent_m0_read),                                //                         .read
		.uav_write              (sys_hps_f2h_sdram0_data_agent_m0_write),                               //                         .write
		.uav_waitrequest        (sys_hps_f2h_sdram0_data_agent_m0_waitrequest),                         //                         .waitrequest
		.uav_readdatavalid      (sys_hps_f2h_sdram0_data_agent_m0_readdatavalid),                       //                         .readdatavalid
		.uav_byteenable         (sys_hps_f2h_sdram0_data_agent_m0_byteenable),                          //                         .byteenable
		.uav_readdata           (sys_hps_f2h_sdram0_data_agent_m0_readdata),                            //                         .readdata
		.uav_writedata          (sys_hps_f2h_sdram0_data_agent_m0_writedata),                           //                         .writedata
		.uav_lock               (sys_hps_f2h_sdram0_data_agent_m0_lock),                                //                         .lock
		.uav_debugaccess        (sys_hps_f2h_sdram0_data_agent_m0_debugaccess),                         //                         .debugaccess
		.av_address             (sys_hps_f2h_sdram0_data_address),                                      //      avalon_anti_slave_0.address
		.av_write               (sys_hps_f2h_sdram0_data_write),                                        //                         .write
		.av_read                (sys_hps_f2h_sdram0_data_read),                                         //                         .read
		.av_readdata            (sys_hps_f2h_sdram0_data_readdata),                                     //                         .readdata
		.av_writedata           (sys_hps_f2h_sdram0_data_writedata),                                    //                         .writedata
		.av_burstcount          (sys_hps_f2h_sdram0_data_burstcount),                                   //                         .burstcount
		.av_byteenable          (sys_hps_f2h_sdram0_data_byteenable),                                   //                         .byteenable
		.av_readdatavalid       (sys_hps_f2h_sdram0_data_readdatavalid),                                //                         .readdatavalid
		.av_waitrequest         (sys_hps_f2h_sdram0_data_waitrequest),                                  //                         .waitrequest
		.av_begintransfer       (),                                                                     //              (terminated)
		.av_beginbursttransfer  (),                                                                     //              (terminated)
		.av_writebyteenable     (),                                                                     //              (terminated)
		.av_lock                (),                                                                     //              (terminated)
		.av_chipselect          (),                                                                     //              (terminated)
		.av_clken               (),                                                                     //              (terminated)
		.uav_clken              (1'b0),                                                                 //              (terminated)
		.av_debugaccess         (),                                                                     //              (terminated)
		.av_outputenable        (),                                                                     //              (terminated)
		.uav_response           (),                                                                     //              (terminated)
		.av_response            (2'b00),                                                                //              (terminated)
		.uav_writeresponsevalid (),                                                                     //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                                  //              (terminated)
	);

	altera_merlin_axi_master_ni #(
		.ID_WIDTH                  (1),
		.ADDR_WIDTH                (32),
		.RDATA_WIDTH               (64),
		.WDATA_WIDTH               (64),
		.ADDR_USER_WIDTH           (1),
		.DATA_USER_WIDTH           (1),
		.AXI_BURST_LENGTH_WIDTH    (4),
		.AXI_LOCK_WIDTH            (2),
		.AXI_VERSION               ("AXI3"),
		.WRITE_ISSUING_CAPABILITY  (1),
		.READ_ISSUING_CAPABILITY   (8),
		.PKT_BEGIN_BURST           (136),
		.PKT_CACHE_H               (147),
		.PKT_CACHE_L               (144),
		.PKT_ADDR_SIDEBAND_H       (134),
		.PKT_ADDR_SIDEBAND_L       (134),
		.PKT_PROTECTION_H          (143),
		.PKT_PROTECTION_L          (141),
		.PKT_BURST_SIZE_H          (131),
		.PKT_BURST_SIZE_L          (129),
		.PKT_BURST_TYPE_H          (133),
		.PKT_BURST_TYPE_L          (132),
		.PKT_RESPONSE_STATUS_L     (148),
		.PKT_RESPONSE_STATUS_H     (149),
		.PKT_BURSTWRAP_H           (128),
		.PKT_BURSTWRAP_L           (121),
		.PKT_BYTE_CNT_H            (120),
		.PKT_BYTE_CNT_L            (110),
		.PKT_ADDR_H                (103),
		.PKT_ADDR_L                (72),
		.PKT_TRANS_EXCLUSIVE       (109),
		.PKT_TRANS_LOCK            (108),
		.PKT_TRANS_COMPRESSED_READ (104),
		.PKT_TRANS_POSTED          (105),
		.PKT_TRANS_WRITE           (106),
		.PKT_TRANS_READ            (107),
		.PKT_DATA_H                (63),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (71),
		.PKT_BYTEEN_L              (64),
		.PKT_SRC_ID_H              (138),
		.PKT_SRC_ID_L              (138),
		.PKT_DEST_ID_H             (139),
		.PKT_DEST_ID_L             (139),
		.PKT_THREAD_ID_H           (140),
		.PKT_THREAD_ID_L           (140),
		.PKT_QOS_L                 (137),
		.PKT_QOS_H                 (137),
		.PKT_ORI_BURST_SIZE_L      (150),
		.PKT_ORI_BURST_SIZE_H      (152),
		.PKT_DATA_SIDEBAND_H       (135),
		.PKT_DATA_SIDEBAND_L       (135),
		.ST_DATA_W                 (153),
		.ST_CHANNEL_W              (2),
		.ID                        (0)
	) hdmi_dmac_0_m_src_axi_agent (
		.aclk                   (sys_hps_h2f_user1_clock_clk),                              //              clk.clk
		.aresetn                (~hdmi_dmac_0_m_src_axi_reset_reset_bridge_in_reset_reset), //        clk_reset.reset_n
		.write_cp_valid         (hdmi_dmac_0_m_src_axi_agent_write_cp_valid),               //         write_cp.valid
		.write_cp_data          (hdmi_dmac_0_m_src_axi_agent_write_cp_data),                //                 .data
		.write_cp_startofpacket (hdmi_dmac_0_m_src_axi_agent_write_cp_startofpacket),       //                 .startofpacket
		.write_cp_endofpacket   (hdmi_dmac_0_m_src_axi_agent_write_cp_endofpacket),         //                 .endofpacket
		.write_cp_ready         (hdmi_dmac_0_m_src_axi_agent_write_cp_ready),               //                 .ready
		.write_rp_valid         (rsp_mux_src_valid),                                        //         write_rp.valid
		.write_rp_data          (rsp_mux_src_data),                                         //                 .data
		.write_rp_channel       (rsp_mux_src_channel),                                      //                 .channel
		.write_rp_startofpacket (rsp_mux_src_startofpacket),                                //                 .startofpacket
		.write_rp_endofpacket   (rsp_mux_src_endofpacket),                                  //                 .endofpacket
		.write_rp_ready         (rsp_mux_src_ready),                                        //                 .ready
		.read_cp_valid          (hdmi_dmac_0_m_src_axi_agent_read_cp_valid),                //          read_cp.valid
		.read_cp_data           (hdmi_dmac_0_m_src_axi_agent_read_cp_data),                 //                 .data
		.read_cp_startofpacket  (hdmi_dmac_0_m_src_axi_agent_read_cp_startofpacket),        //                 .startofpacket
		.read_cp_endofpacket    (hdmi_dmac_0_m_src_axi_agent_read_cp_endofpacket),          //                 .endofpacket
		.read_cp_ready          (hdmi_dmac_0_m_src_axi_agent_read_cp_ready),                //                 .ready
		.read_rp_valid          (rsp_mux_001_src_valid),                                    //          read_rp.valid
		.read_rp_data           (rsp_mux_001_src_data),                                     //                 .data
		.read_rp_channel        (rsp_mux_001_src_channel),                                  //                 .channel
		.read_rp_startofpacket  (rsp_mux_001_src_startofpacket),                            //                 .startofpacket
		.read_rp_endofpacket    (rsp_mux_001_src_endofpacket),                              //                 .endofpacket
		.read_rp_ready          (rsp_mux_001_src_ready),                                    //                 .ready
		.awid                   (hdmi_dmac_0_m_src_axi_awid),                               // altera_axi_slave.awid
		.awaddr                 (hdmi_dmac_0_m_src_axi_awaddr),                             //                 .awaddr
		.awlen                  (hdmi_dmac_0_m_src_axi_awlen),                              //                 .awlen
		.awsize                 (hdmi_dmac_0_m_src_axi_awsize),                             //                 .awsize
		.awburst                (hdmi_dmac_0_m_src_axi_awburst),                            //                 .awburst
		.awlock                 (hdmi_dmac_0_m_src_axi_awlock),                             //                 .awlock
		.awcache                (hdmi_dmac_0_m_src_axi_awcache),                            //                 .awcache
		.awprot                 (hdmi_dmac_0_m_src_axi_awprot),                             //                 .awprot
		.awvalid                (hdmi_dmac_0_m_src_axi_awvalid),                            //                 .awvalid
		.awready                (hdmi_dmac_0_m_src_axi_awready),                            //                 .awready
		.wid                    (hdmi_dmac_0_m_src_axi_wid),                                //                 .wid
		.wdata                  (hdmi_dmac_0_m_src_axi_wdata),                              //                 .wdata
		.wstrb                  (hdmi_dmac_0_m_src_axi_wstrb),                              //                 .wstrb
		.wlast                  (hdmi_dmac_0_m_src_axi_wlast),                              //                 .wlast
		.wvalid                 (hdmi_dmac_0_m_src_axi_wvalid),                             //                 .wvalid
		.wready                 (hdmi_dmac_0_m_src_axi_wready),                             //                 .wready
		.bid                    (hdmi_dmac_0_m_src_axi_bid),                                //                 .bid
		.bresp                  (hdmi_dmac_0_m_src_axi_bresp),                              //                 .bresp
		.bvalid                 (hdmi_dmac_0_m_src_axi_bvalid),                             //                 .bvalid
		.bready                 (hdmi_dmac_0_m_src_axi_bready),                             //                 .bready
		.arid                   (hdmi_dmac_0_m_src_axi_arid),                               //                 .arid
		.araddr                 (hdmi_dmac_0_m_src_axi_araddr),                             //                 .araddr
		.arlen                  (hdmi_dmac_0_m_src_axi_arlen),                              //                 .arlen
		.arsize                 (hdmi_dmac_0_m_src_axi_arsize),                             //                 .arsize
		.arburst                (hdmi_dmac_0_m_src_axi_arburst),                            //                 .arburst
		.arlock                 (hdmi_dmac_0_m_src_axi_arlock),                             //                 .arlock
		.arcache                (hdmi_dmac_0_m_src_axi_arcache),                            //                 .arcache
		.arprot                 (hdmi_dmac_0_m_src_axi_arprot),                             //                 .arprot
		.arvalid                (hdmi_dmac_0_m_src_axi_arvalid),                            //                 .arvalid
		.arready                (hdmi_dmac_0_m_src_axi_arready),                            //                 .arready
		.rid                    (hdmi_dmac_0_m_src_axi_rid),                                //                 .rid
		.rdata                  (hdmi_dmac_0_m_src_axi_rdata),                              //                 .rdata
		.rresp                  (hdmi_dmac_0_m_src_axi_rresp),                              //                 .rresp
		.rlast                  (hdmi_dmac_0_m_src_axi_rlast),                              //                 .rlast
		.rvalid                 (hdmi_dmac_0_m_src_axi_rvalid),                             //                 .rvalid
		.rready                 (hdmi_dmac_0_m_src_axi_rready),                             //                 .rready
		.awuser                 (1'b0),                                                     //      (terminated)
		.aruser                 (1'b0),                                                     //      (terminated)
		.awqos                  (4'b0000),                                                  //      (terminated)
		.arqos                  (4'b0000),                                                  //      (terminated)
		.awregion               (4'b0000),                                                  //      (terminated)
		.arregion               (4'b0000),                                                  //      (terminated)
		.wuser                  (1'b0),                                                     //      (terminated)
		.ruser                  (),                                                         //      (terminated)
		.buser                  ()                                                          //      (terminated)
	);

	altera_merlin_slave_agent #(
		.PKT_ORI_BURST_SIZE_H      (152),
		.PKT_ORI_BURST_SIZE_L      (150),
		.PKT_RESPONSE_STATUS_H     (149),
		.PKT_RESPONSE_STATUS_L     (148),
		.PKT_BURST_SIZE_H          (131),
		.PKT_BURST_SIZE_L          (129),
		.PKT_TRANS_LOCK            (108),
		.PKT_BEGIN_BURST           (136),
		.PKT_PROTECTION_H          (143),
		.PKT_PROTECTION_L          (141),
		.PKT_BURSTWRAP_H           (128),
		.PKT_BURSTWRAP_L           (121),
		.PKT_BYTE_CNT_H            (120),
		.PKT_BYTE_CNT_L            (110),
		.PKT_ADDR_H                (103),
		.PKT_ADDR_L                (72),
		.PKT_TRANS_COMPRESSED_READ (104),
		.PKT_TRANS_POSTED          (105),
		.PKT_TRANS_WRITE           (106),
		.PKT_TRANS_READ            (107),
		.PKT_DATA_H                (63),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (71),
		.PKT_BYTEEN_L              (64),
		.PKT_SRC_ID_H              (138),
		.PKT_SRC_ID_L              (138),
		.PKT_DEST_ID_H             (139),
		.PKT_DEST_ID_L             (139),
		.PKT_SYMBOL_W              (8),
		.ST_CHANNEL_W              (2),
		.ST_DATA_W                 (153),
		.AVS_BURSTCOUNT_W          (11),
		.SUPPRESS_0_BYTEEN_CMD     (0),
		.PREVENT_FIFO_OVERFLOW     (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0),
		.ECC_ENABLE                (0)
	) sys_hps_f2h_sdram0_data_agent (
		.clk                     (sys_hps_h2f_user1_clock_clk),                                          //             clk.clk
		.reset                   (sys_hps_f2h_sdram0_data_translator_reset_reset_bridge_in_reset_reset), //       clk_reset.reset
		.m0_address              (sys_hps_f2h_sdram0_data_agent_m0_address),                             //              m0.address
		.m0_burstcount           (sys_hps_f2h_sdram0_data_agent_m0_burstcount),                          //                .burstcount
		.m0_byteenable           (sys_hps_f2h_sdram0_data_agent_m0_byteenable),                          //                .byteenable
		.m0_debugaccess          (sys_hps_f2h_sdram0_data_agent_m0_debugaccess),                         //                .debugaccess
		.m0_lock                 (sys_hps_f2h_sdram0_data_agent_m0_lock),                                //                .lock
		.m0_readdata             (sys_hps_f2h_sdram0_data_agent_m0_readdata),                            //                .readdata
		.m0_readdatavalid        (sys_hps_f2h_sdram0_data_agent_m0_readdatavalid),                       //                .readdatavalid
		.m0_read                 (sys_hps_f2h_sdram0_data_agent_m0_read),                                //                .read
		.m0_waitrequest          (sys_hps_f2h_sdram0_data_agent_m0_waitrequest),                         //                .waitrequest
		.m0_writedata            (sys_hps_f2h_sdram0_data_agent_m0_writedata),                           //                .writedata
		.m0_write                (sys_hps_f2h_sdram0_data_agent_m0_write),                               //                .write
		.rp_endofpacket          (sys_hps_f2h_sdram0_data_agent_rp_endofpacket),                         //              rp.endofpacket
		.rp_ready                (sys_hps_f2h_sdram0_data_agent_rp_ready),                               //                .ready
		.rp_valid                (sys_hps_f2h_sdram0_data_agent_rp_valid),                               //                .valid
		.rp_data                 (sys_hps_f2h_sdram0_data_agent_rp_data),                                //                .data
		.rp_startofpacket        (sys_hps_f2h_sdram0_data_agent_rp_startofpacket),                       //                .startofpacket
		.cp_ready                (agent_pipeline_source0_ready),                                         //              cp.ready
		.cp_valid                (agent_pipeline_source0_valid),                                         //                .valid
		.cp_data                 (agent_pipeline_source0_data),                                          //                .data
		.cp_startofpacket        (agent_pipeline_source0_startofpacket),                                 //                .startofpacket
		.cp_endofpacket          (agent_pipeline_source0_endofpacket),                                   //                .endofpacket
		.cp_channel              (agent_pipeline_source0_channel),                                       //                .channel
		.rf_sink_ready           (sys_hps_f2h_sdram0_data_agent_rsp_fifo_out_ready),                     //         rf_sink.ready
		.rf_sink_valid           (sys_hps_f2h_sdram0_data_agent_rsp_fifo_out_valid),                     //                .valid
		.rf_sink_startofpacket   (sys_hps_f2h_sdram0_data_agent_rsp_fifo_out_startofpacket),             //                .startofpacket
		.rf_sink_endofpacket     (sys_hps_f2h_sdram0_data_agent_rsp_fifo_out_endofpacket),               //                .endofpacket
		.rf_sink_data            (sys_hps_f2h_sdram0_data_agent_rsp_fifo_out_data),                      //                .data
		.rf_source_ready         (sys_hps_f2h_sdram0_data_agent_rf_source_ready),                        //       rf_source.ready
		.rf_source_valid         (sys_hps_f2h_sdram0_data_agent_rf_source_valid),                        //                .valid
		.rf_source_startofpacket (sys_hps_f2h_sdram0_data_agent_rf_source_startofpacket),                //                .startofpacket
		.rf_source_endofpacket   (sys_hps_f2h_sdram0_data_agent_rf_source_endofpacket),                  //                .endofpacket
		.rf_source_data          (sys_hps_f2h_sdram0_data_agent_rf_source_data),                         //                .data
		.rdata_fifo_sink_ready   (avalon_st_adapter_out_0_ready),                                        // rdata_fifo_sink.ready
		.rdata_fifo_sink_valid   (avalon_st_adapter_out_0_valid),                                        //                .valid
		.rdata_fifo_sink_data    (avalon_st_adapter_out_0_data),                                         //                .data
		.rdata_fifo_sink_error   (avalon_st_adapter_out_0_error),                                        //                .error
		.rdata_fifo_src_ready    (sys_hps_f2h_sdram0_data_agent_rdata_fifo_src_ready),                   //  rdata_fifo_src.ready
		.rdata_fifo_src_valid    (sys_hps_f2h_sdram0_data_agent_rdata_fifo_src_valid),                   //                .valid
		.rdata_fifo_src_data     (sys_hps_f2h_sdram0_data_agent_rdata_fifo_src_data),                    //                .data
		.m0_response             (2'b00),                                                                //     (terminated)
		.m0_writeresponsevalid   (1'b0)                                                                  //     (terminated)
	);

	altera_avalon_sc_fifo #(
		.SYMBOLS_PER_BEAT    (1),
		.BITS_PER_SYMBOL     (154),
		.FIFO_DEPTH          (15),
		.CHANNEL_WIDTH       (0),
		.ERROR_WIDTH         (0),
		.USE_PACKETS         (1),
		.USE_FILL_LEVEL      (0),
		.EMPTY_LATENCY       (1),
		.USE_MEMORY_BLOCKS   (0),
		.USE_STORE_FORWARD   (0),
		.USE_ALMOST_FULL_IF  (0),
		.USE_ALMOST_EMPTY_IF (0)
	) sys_hps_f2h_sdram0_data_agent_rsp_fifo (
		.clk               (sys_hps_h2f_user1_clock_clk),                                          //       clk.clk
		.reset             (sys_hps_f2h_sdram0_data_translator_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.in_data           (sys_hps_f2h_sdram0_data_agent_rf_source_data),                         //        in.data
		.in_valid          (sys_hps_f2h_sdram0_data_agent_rf_source_valid),                        //          .valid
		.in_ready          (sys_hps_f2h_sdram0_data_agent_rf_source_ready),                        //          .ready
		.in_startofpacket  (sys_hps_f2h_sdram0_data_agent_rf_source_startofpacket),                //          .startofpacket
		.in_endofpacket    (sys_hps_f2h_sdram0_data_agent_rf_source_endofpacket),                  //          .endofpacket
		.out_data          (sys_hps_f2h_sdram0_data_agent_rsp_fifo_out_data),                      //       out.data
		.out_valid         (sys_hps_f2h_sdram0_data_agent_rsp_fifo_out_valid),                     //          .valid
		.out_ready         (sys_hps_f2h_sdram0_data_agent_rsp_fifo_out_ready),                     //          .ready
		.out_startofpacket (sys_hps_f2h_sdram0_data_agent_rsp_fifo_out_startofpacket),             //          .startofpacket
		.out_endofpacket   (sys_hps_f2h_sdram0_data_agent_rsp_fifo_out_endofpacket),               //          .endofpacket
		.csr_address       (2'b00),                                                                // (terminated)
		.csr_read          (1'b0),                                                                 // (terminated)
		.csr_write         (1'b0),                                                                 // (terminated)
		.csr_readdata      (),                                                                     // (terminated)
		.csr_writedata     (32'b00000000000000000000000000000000),                                 // (terminated)
		.almost_full_data  (),                                                                     // (terminated)
		.almost_empty_data (),                                                                     // (terminated)
		.in_empty          (1'b0),                                                                 // (terminated)
		.out_empty         (),                                                                     // (terminated)
		.in_error          (1'b0),                                                                 // (terminated)
		.out_error         (),                                                                     // (terminated)
		.in_channel        (1'b0),                                                                 // (terminated)
		.out_channel       ()                                                                      // (terminated)
	);

	altera_avalon_sc_fifo #(
		.SYMBOLS_PER_BEAT    (1),
		.BITS_PER_SYMBOL     (66),
		.FIFO_DEPTH          (256),
		.CHANNEL_WIDTH       (0),
		.ERROR_WIDTH         (0),
		.USE_PACKETS         (0),
		.USE_FILL_LEVEL      (0),
		.EMPTY_LATENCY       (3),
		.USE_MEMORY_BLOCKS   (1),
		.USE_STORE_FORWARD   (0),
		.USE_ALMOST_FULL_IF  (0),
		.USE_ALMOST_EMPTY_IF (0)
	) sys_hps_f2h_sdram0_data_agent_rdata_fifo (
		.clk               (sys_hps_h2f_user1_clock_clk),                                          //       clk.clk
		.reset             (sys_hps_f2h_sdram0_data_translator_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.in_data           (sys_hps_f2h_sdram0_data_agent_rdata_fifo_src_data),                    //        in.data
		.in_valid          (sys_hps_f2h_sdram0_data_agent_rdata_fifo_src_valid),                   //          .valid
		.in_ready          (sys_hps_f2h_sdram0_data_agent_rdata_fifo_src_ready),                   //          .ready
		.out_data          (sys_hps_f2h_sdram0_data_agent_rdata_fifo_out_data),                    //       out.data
		.out_valid         (sys_hps_f2h_sdram0_data_agent_rdata_fifo_out_valid),                   //          .valid
		.out_ready         (sys_hps_f2h_sdram0_data_agent_rdata_fifo_out_ready),                   //          .ready
		.csr_address       (2'b00),                                                                // (terminated)
		.csr_read          (1'b0),                                                                 // (terminated)
		.csr_write         (1'b0),                                                                 // (terminated)
		.csr_readdata      (),                                                                     // (terminated)
		.csr_writedata     (32'b00000000000000000000000000000000),                                 // (terminated)
		.almost_full_data  (),                                                                     // (terminated)
		.almost_empty_data (),                                                                     // (terminated)
		.in_startofpacket  (1'b0),                                                                 // (terminated)
		.in_endofpacket    (1'b0),                                                                 // (terminated)
		.out_startofpacket (),                                                                     // (terminated)
		.out_endofpacket   (),                                                                     // (terminated)
		.in_empty          (1'b0),                                                                 // (terminated)
		.out_empty         (),                                                                     // (terminated)
		.in_error          (1'b0),                                                                 // (terminated)
		.out_error         (),                                                                     // (terminated)
		.in_channel        (1'b0),                                                                 // (terminated)
		.out_channel       ()                                                                      // (terminated)
	);

	system_bd_mm_interconnect_2_router router (
		.sink_ready         (hdmi_dmac_0_m_src_axi_agent_write_cp_ready),              //      sink.ready
		.sink_valid         (hdmi_dmac_0_m_src_axi_agent_write_cp_valid),              //          .valid
		.sink_data          (hdmi_dmac_0_m_src_axi_agent_write_cp_data),               //          .data
		.sink_startofpacket (hdmi_dmac_0_m_src_axi_agent_write_cp_startofpacket),      //          .startofpacket
		.sink_endofpacket   (hdmi_dmac_0_m_src_axi_agent_write_cp_endofpacket),        //          .endofpacket
		.clk                (sys_hps_h2f_user1_clock_clk),                             //       clk.clk
		.reset              (hdmi_dmac_0_m_src_axi_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (router_src_ready),                                        //       src.ready
		.src_valid          (router_src_valid),                                        //          .valid
		.src_data           (router_src_data),                                         //          .data
		.src_channel        (router_src_channel),                                      //          .channel
		.src_startofpacket  (router_src_startofpacket),                                //          .startofpacket
		.src_endofpacket    (router_src_endofpacket)                                   //          .endofpacket
	);

	system_bd_mm_interconnect_2_router router_001 (
		.sink_ready         (hdmi_dmac_0_m_src_axi_agent_read_cp_ready),               //      sink.ready
		.sink_valid         (hdmi_dmac_0_m_src_axi_agent_read_cp_valid),               //          .valid
		.sink_data          (hdmi_dmac_0_m_src_axi_agent_read_cp_data),                //          .data
		.sink_startofpacket (hdmi_dmac_0_m_src_axi_agent_read_cp_startofpacket),       //          .startofpacket
		.sink_endofpacket   (hdmi_dmac_0_m_src_axi_agent_read_cp_endofpacket),         //          .endofpacket
		.clk                (sys_hps_h2f_user1_clock_clk),                             //       clk.clk
		.reset              (hdmi_dmac_0_m_src_axi_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (router_001_src_ready),                                    //       src.ready
		.src_valid          (router_001_src_valid),                                    //          .valid
		.src_data           (router_001_src_data),                                     //          .data
		.src_channel        (router_001_src_channel),                                  //          .channel
		.src_startofpacket  (router_001_src_startofpacket),                            //          .startofpacket
		.src_endofpacket    (router_001_src_endofpacket)                               //          .endofpacket
	);

	system_bd_mm_interconnect_2_router_002 router_002 (
		.sink_ready         (agent_pipeline_001_source0_ready),                                     //      sink.ready
		.sink_valid         (agent_pipeline_001_source0_valid),                                     //          .valid
		.sink_data          (agent_pipeline_001_source0_data),                                      //          .data
		.sink_startofpacket (agent_pipeline_001_source0_startofpacket),                             //          .startofpacket
		.sink_endofpacket   (agent_pipeline_001_source0_endofpacket),                               //          .endofpacket
		.clk                (sys_hps_h2f_user1_clock_clk),                                          //       clk.clk
		.reset              (sys_hps_f2h_sdram0_data_translator_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (router_002_src_ready),                                                 //       src.ready
		.src_valid          (router_002_src_valid),                                                 //          .valid
		.src_data           (router_002_src_data),                                                  //          .data
		.src_channel        (router_002_src_channel),                                               //          .channel
		.src_startofpacket  (router_002_src_startofpacket),                                         //          .startofpacket
		.src_endofpacket    (router_002_src_endofpacket)                                            //          .endofpacket
	);

	altera_merlin_burst_adapter #(
		.PKT_ADDR_H                (103),
		.PKT_ADDR_L                (72),
		.PKT_BEGIN_BURST           (136),
		.PKT_BYTE_CNT_H            (120),
		.PKT_BYTE_CNT_L            (110),
		.PKT_BYTEEN_H              (71),
		.PKT_BYTEEN_L              (64),
		.PKT_BURST_SIZE_H          (131),
		.PKT_BURST_SIZE_L          (129),
		.PKT_BURST_TYPE_H          (133),
		.PKT_BURST_TYPE_L          (132),
		.PKT_BURSTWRAP_H           (128),
		.PKT_BURSTWRAP_L           (121),
		.PKT_TRANS_COMPRESSED_READ (104),
		.PKT_TRANS_WRITE           (106),
		.PKT_TRANS_READ            (107),
		.OUT_NARROW_SIZE           (0),
		.IN_NARROW_SIZE            (1),
		.OUT_FIXED                 (0),
		.OUT_COMPLETE_WRAP         (0),
		.ST_DATA_W                 (153),
		.ST_CHANNEL_W              (2),
		.OUT_BYTE_CNT_H            (120),
		.OUT_BURSTWRAP_H           (128),
		.COMPRESSED_READ_SUPPORT   (1),
		.BYTEENABLE_SYNTHESIS      (1),
		.PIPE_INPUTS               (0),
		.NO_WRAP_SUPPORT           (0),
		.INCOMPLETE_WRAP_SUPPORT   (0),
		.BURSTWRAP_CONST_MASK      (0),
		.BURSTWRAP_CONST_VALUE     (0),
		.ADAPTER_VERSION           ("new")
	) sys_hps_f2h_sdram0_data_burst_adapter (
		.clk                   (sys_hps_h2f_user1_clock_clk),                                          //       cr0.clk
		.reset                 (sys_hps_f2h_sdram0_data_translator_reset_reset_bridge_in_reset_reset), // cr0_reset.reset
		.sink0_valid           (cmd_mux_src_valid),                                                    //     sink0.valid
		.sink0_data            (cmd_mux_src_data),                                                     //          .data
		.sink0_channel         (cmd_mux_src_channel),                                                  //          .channel
		.sink0_startofpacket   (cmd_mux_src_startofpacket),                                            //          .startofpacket
		.sink0_endofpacket     (cmd_mux_src_endofpacket),                                              //          .endofpacket
		.sink0_ready           (cmd_mux_src_ready),                                                    //          .ready
		.source0_valid         (sys_hps_f2h_sdram0_data_burst_adapter_source0_valid),                  //   source0.valid
		.source0_data          (sys_hps_f2h_sdram0_data_burst_adapter_source0_data),                   //          .data
		.source0_channel       (sys_hps_f2h_sdram0_data_burst_adapter_source0_channel),                //          .channel
		.source0_startofpacket (sys_hps_f2h_sdram0_data_burst_adapter_source0_startofpacket),          //          .startofpacket
		.source0_endofpacket   (sys_hps_f2h_sdram0_data_burst_adapter_source0_endofpacket),            //          .endofpacket
		.source0_ready         (sys_hps_f2h_sdram0_data_burst_adapter_source0_ready)                   //          .ready
	);

	system_bd_mm_interconnect_2_cmd_demux cmd_demux (
		.clk                (sys_hps_h2f_user1_clock_clk),                             //       clk.clk
		.reset              (hdmi_dmac_0_m_src_axi_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (router_src_ready),                                        //      sink.ready
		.sink_channel       (router_src_channel),                                      //          .channel
		.sink_data          (router_src_data),                                         //          .data
		.sink_startofpacket (router_src_startofpacket),                                //          .startofpacket
		.sink_endofpacket   (router_src_endofpacket),                                  //          .endofpacket
		.sink_valid         (router_src_valid),                                        //          .valid
		.src0_ready         (cmd_demux_src0_ready),                                    //      src0.ready
		.src0_valid         (cmd_demux_src0_valid),                                    //          .valid
		.src0_data          (cmd_demux_src0_data),                                     //          .data
		.src0_channel       (cmd_demux_src0_channel),                                  //          .channel
		.src0_startofpacket (cmd_demux_src0_startofpacket),                            //          .startofpacket
		.src0_endofpacket   (cmd_demux_src0_endofpacket)                               //          .endofpacket
	);

	system_bd_mm_interconnect_2_cmd_demux cmd_demux_001 (
		.clk                (sys_hps_h2f_user1_clock_clk),                             //       clk.clk
		.reset              (hdmi_dmac_0_m_src_axi_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (router_001_src_ready),                                    //      sink.ready
		.sink_channel       (router_001_src_channel),                                  //          .channel
		.sink_data          (router_001_src_data),                                     //          .data
		.sink_startofpacket (router_001_src_startofpacket),                            //          .startofpacket
		.sink_endofpacket   (router_001_src_endofpacket),                              //          .endofpacket
		.sink_valid         (router_001_src_valid),                                    //          .valid
		.src0_ready         (cmd_demux_001_src0_ready),                                //      src0.ready
		.src0_valid         (cmd_demux_001_src0_valid),                                //          .valid
		.src0_data          (cmd_demux_001_src0_data),                                 //          .data
		.src0_channel       (cmd_demux_001_src0_channel),                              //          .channel
		.src0_startofpacket (cmd_demux_001_src0_startofpacket),                        //          .startofpacket
		.src0_endofpacket   (cmd_demux_001_src0_endofpacket)                           //          .endofpacket
	);

	system_bd_mm_interconnect_2_cmd_mux cmd_mux (
		.clk                 (sys_hps_h2f_user1_clock_clk),                                          //       clk.clk
		.reset               (sys_hps_f2h_sdram0_data_translator_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (cmd_mux_src_ready),                                                    //       src.ready
		.src_valid           (cmd_mux_src_valid),                                                    //          .valid
		.src_data            (cmd_mux_src_data),                                                     //          .data
		.src_channel         (cmd_mux_src_channel),                                                  //          .channel
		.src_startofpacket   (cmd_mux_src_startofpacket),                                            //          .startofpacket
		.src_endofpacket     (cmd_mux_src_endofpacket),                                              //          .endofpacket
		.sink0_ready         (mux_pipeline_source0_ready),                                           //     sink0.ready
		.sink0_valid         (mux_pipeline_source0_valid),                                           //          .valid
		.sink0_channel       (mux_pipeline_source0_channel),                                         //          .channel
		.sink0_data          (mux_pipeline_source0_data),                                            //          .data
		.sink0_startofpacket (mux_pipeline_source0_startofpacket),                                   //          .startofpacket
		.sink0_endofpacket   (mux_pipeline_source0_endofpacket),                                     //          .endofpacket
		.sink1_ready         (mux_pipeline_001_source0_ready),                                       //     sink1.ready
		.sink1_valid         (mux_pipeline_001_source0_valid),                                       //          .valid
		.sink1_channel       (mux_pipeline_001_source0_channel),                                     //          .channel
		.sink1_data          (mux_pipeline_001_source0_data),                                        //          .data
		.sink1_startofpacket (mux_pipeline_001_source0_startofpacket),                               //          .startofpacket
		.sink1_endofpacket   (mux_pipeline_001_source0_endofpacket)                                  //          .endofpacket
	);

	system_bd_mm_interconnect_2_rsp_demux rsp_demux (
		.clk                (sys_hps_h2f_user1_clock_clk),                                          //       clk.clk
		.reset              (sys_hps_f2h_sdram0_data_translator_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (router_002_src_ready),                                                 //      sink.ready
		.sink_channel       (router_002_src_channel),                                               //          .channel
		.sink_data          (router_002_src_data),                                                  //          .data
		.sink_startofpacket (router_002_src_startofpacket),                                         //          .startofpacket
		.sink_endofpacket   (router_002_src_endofpacket),                                           //          .endofpacket
		.sink_valid         (router_002_src_valid),                                                 //          .valid
		.src0_ready         (rsp_demux_src0_ready),                                                 //      src0.ready
		.src0_valid         (rsp_demux_src0_valid),                                                 //          .valid
		.src0_data          (rsp_demux_src0_data),                                                  //          .data
		.src0_channel       (rsp_demux_src0_channel),                                               //          .channel
		.src0_startofpacket (rsp_demux_src0_startofpacket),                                         //          .startofpacket
		.src0_endofpacket   (rsp_demux_src0_endofpacket),                                           //          .endofpacket
		.src1_ready         (rsp_demux_src1_ready),                                                 //      src1.ready
		.src1_valid         (rsp_demux_src1_valid),                                                 //          .valid
		.src1_data          (rsp_demux_src1_data),                                                  //          .data
		.src1_channel       (rsp_demux_src1_channel),                                               //          .channel
		.src1_startofpacket (rsp_demux_src1_startofpacket),                                         //          .startofpacket
		.src1_endofpacket   (rsp_demux_src1_endofpacket)                                            //          .endofpacket
	);

	system_bd_mm_interconnect_2_rsp_mux rsp_mux (
		.clk                 (sys_hps_h2f_user1_clock_clk),                             //       clk.clk
		.reset               (hdmi_dmac_0_m_src_axi_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (rsp_mux_src_ready),                                       //       src.ready
		.src_valid           (rsp_mux_src_valid),                                       //          .valid
		.src_data            (rsp_mux_src_data),                                        //          .data
		.src_channel         (rsp_mux_src_channel),                                     //          .channel
		.src_startofpacket   (rsp_mux_src_startofpacket),                               //          .startofpacket
		.src_endofpacket     (rsp_mux_src_endofpacket),                                 //          .endofpacket
		.sink0_ready         (mux_pipeline_002_source0_ready),                          //     sink0.ready
		.sink0_valid         (mux_pipeline_002_source0_valid),                          //          .valid
		.sink0_channel       (mux_pipeline_002_source0_channel),                        //          .channel
		.sink0_data          (mux_pipeline_002_source0_data),                           //          .data
		.sink0_startofpacket (mux_pipeline_002_source0_startofpacket),                  //          .startofpacket
		.sink0_endofpacket   (mux_pipeline_002_source0_endofpacket)                     //          .endofpacket
	);

	system_bd_mm_interconnect_2_rsp_mux rsp_mux_001 (
		.clk                 (sys_hps_h2f_user1_clock_clk),                             //       clk.clk
		.reset               (hdmi_dmac_0_m_src_axi_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (rsp_mux_001_src_ready),                                   //       src.ready
		.src_valid           (rsp_mux_001_src_valid),                                   //          .valid
		.src_data            (rsp_mux_001_src_data),                                    //          .data
		.src_channel         (rsp_mux_001_src_channel),                                 //          .channel
		.src_startofpacket   (rsp_mux_001_src_startofpacket),                           //          .startofpacket
		.src_endofpacket     (rsp_mux_001_src_endofpacket),                             //          .endofpacket
		.sink0_ready         (mux_pipeline_003_source0_ready),                          //     sink0.ready
		.sink0_valid         (mux_pipeline_003_source0_valid),                          //          .valid
		.sink0_channel       (mux_pipeline_003_source0_channel),                        //          .channel
		.sink0_data          (mux_pipeline_003_source0_data),                           //          .data
		.sink0_startofpacket (mux_pipeline_003_source0_startofpacket),                  //          .startofpacket
		.sink0_endofpacket   (mux_pipeline_003_source0_endofpacket)                     //          .endofpacket
	);

	altera_avalon_st_pipeline_stage #(
		.SYMBOLS_PER_BEAT (1),
		.BITS_PER_SYMBOL  (153),
		.USE_PACKETS      (1),
		.USE_EMPTY        (0),
		.EMPTY_WIDTH      (0),
		.CHANNEL_WIDTH    (2),
		.PACKET_WIDTH     (2),
		.ERROR_WIDTH      (0),
		.PIPELINE_READY   (1)
	) agent_pipeline (
		.clk               (sys_hps_h2f_user1_clock_clk),                                          //       cr0.clk
		.reset             (sys_hps_f2h_sdram0_data_translator_reset_reset_bridge_in_reset_reset), // cr0_reset.reset
		.in_ready          (sys_hps_f2h_sdram0_data_burst_adapter_source0_ready),                  //     sink0.ready
		.in_valid          (sys_hps_f2h_sdram0_data_burst_adapter_source0_valid),                  //          .valid
		.in_startofpacket  (sys_hps_f2h_sdram0_data_burst_adapter_source0_startofpacket),          //          .startofpacket
		.in_endofpacket    (sys_hps_f2h_sdram0_data_burst_adapter_source0_endofpacket),            //          .endofpacket
		.in_data           (sys_hps_f2h_sdram0_data_burst_adapter_source0_data),                   //          .data
		.in_channel        (sys_hps_f2h_sdram0_data_burst_adapter_source0_channel),                //          .channel
		.out_ready         (agent_pipeline_source0_ready),                                         //   source0.ready
		.out_valid         (agent_pipeline_source0_valid),                                         //          .valid
		.out_startofpacket (agent_pipeline_source0_startofpacket),                                 //          .startofpacket
		.out_endofpacket   (agent_pipeline_source0_endofpacket),                                   //          .endofpacket
		.out_data          (agent_pipeline_source0_data),                                          //          .data
		.out_channel       (agent_pipeline_source0_channel),                                       //          .channel
		.in_empty          (1'b0),                                                                 // (terminated)
		.out_empty         (),                                                                     // (terminated)
		.out_error         (),                                                                     // (terminated)
		.in_error          (1'b0)                                                                  // (terminated)
	);

	altera_avalon_st_pipeline_stage #(
		.SYMBOLS_PER_BEAT (1),
		.BITS_PER_SYMBOL  (153),
		.USE_PACKETS      (1),
		.USE_EMPTY        (0),
		.EMPTY_WIDTH      (0),
		.CHANNEL_WIDTH    (0),
		.PACKET_WIDTH     (2),
		.ERROR_WIDTH      (0),
		.PIPELINE_READY   (1)
	) agent_pipeline_001 (
		.clk               (sys_hps_h2f_user1_clock_clk),                                          //       cr0.clk
		.reset             (sys_hps_f2h_sdram0_data_translator_reset_reset_bridge_in_reset_reset), // cr0_reset.reset
		.in_ready          (sys_hps_f2h_sdram0_data_agent_rp_ready),                               //     sink0.ready
		.in_valid          (sys_hps_f2h_sdram0_data_agent_rp_valid),                               //          .valid
		.in_startofpacket  (sys_hps_f2h_sdram0_data_agent_rp_startofpacket),                       //          .startofpacket
		.in_endofpacket    (sys_hps_f2h_sdram0_data_agent_rp_endofpacket),                         //          .endofpacket
		.in_data           (sys_hps_f2h_sdram0_data_agent_rp_data),                                //          .data
		.out_ready         (agent_pipeline_001_source0_ready),                                     //   source0.ready
		.out_valid         (agent_pipeline_001_source0_valid),                                     //          .valid
		.out_startofpacket (agent_pipeline_001_source0_startofpacket),                             //          .startofpacket
		.out_endofpacket   (agent_pipeline_001_source0_endofpacket),                               //          .endofpacket
		.out_data          (agent_pipeline_001_source0_data),                                      //          .data
		.in_empty          (1'b0),                                                                 // (terminated)
		.out_empty         (),                                                                     // (terminated)
		.out_error         (),                                                                     // (terminated)
		.in_error          (1'b0),                                                                 // (terminated)
		.out_channel       (),                                                                     // (terminated)
		.in_channel        (1'b0)                                                                  // (terminated)
	);

	altera_avalon_st_pipeline_stage #(
		.SYMBOLS_PER_BEAT (1),
		.BITS_PER_SYMBOL  (153),
		.USE_PACKETS      (1),
		.USE_EMPTY        (0),
		.EMPTY_WIDTH      (0),
		.CHANNEL_WIDTH    (2),
		.PACKET_WIDTH     (2),
		.ERROR_WIDTH      (0),
		.PIPELINE_READY   (1)
	) mux_pipeline (
		.clk               (sys_hps_h2f_user1_clock_clk),                                          //       cr0.clk
		.reset             (sys_hps_f2h_sdram0_data_translator_reset_reset_bridge_in_reset_reset), // cr0_reset.reset
		.in_ready          (cmd_demux_src0_ready),                                                 //     sink0.ready
		.in_valid          (cmd_demux_src0_valid),                                                 //          .valid
		.in_startofpacket  (cmd_demux_src0_startofpacket),                                         //          .startofpacket
		.in_endofpacket    (cmd_demux_src0_endofpacket),                                           //          .endofpacket
		.in_data           (cmd_demux_src0_data),                                                  //          .data
		.in_channel        (cmd_demux_src0_channel),                                               //          .channel
		.out_ready         (mux_pipeline_source0_ready),                                           //   source0.ready
		.out_valid         (mux_pipeline_source0_valid),                                           //          .valid
		.out_startofpacket (mux_pipeline_source0_startofpacket),                                   //          .startofpacket
		.out_endofpacket   (mux_pipeline_source0_endofpacket),                                     //          .endofpacket
		.out_data          (mux_pipeline_source0_data),                                            //          .data
		.out_channel       (mux_pipeline_source0_channel),                                         //          .channel
		.in_empty          (1'b0),                                                                 // (terminated)
		.out_empty         (),                                                                     // (terminated)
		.out_error         (),                                                                     // (terminated)
		.in_error          (1'b0)                                                                  // (terminated)
	);

	altera_avalon_st_pipeline_stage #(
		.SYMBOLS_PER_BEAT (1),
		.BITS_PER_SYMBOL  (153),
		.USE_PACKETS      (1),
		.USE_EMPTY        (0),
		.EMPTY_WIDTH      (0),
		.CHANNEL_WIDTH    (2),
		.PACKET_WIDTH     (2),
		.ERROR_WIDTH      (0),
		.PIPELINE_READY   (1)
	) mux_pipeline_001 (
		.clk               (sys_hps_h2f_user1_clock_clk),                                          //       cr0.clk
		.reset             (sys_hps_f2h_sdram0_data_translator_reset_reset_bridge_in_reset_reset), // cr0_reset.reset
		.in_ready          (cmd_demux_001_src0_ready),                                             //     sink0.ready
		.in_valid          (cmd_demux_001_src0_valid),                                             //          .valid
		.in_startofpacket  (cmd_demux_001_src0_startofpacket),                                     //          .startofpacket
		.in_endofpacket    (cmd_demux_001_src0_endofpacket),                                       //          .endofpacket
		.in_data           (cmd_demux_001_src0_data),                                              //          .data
		.in_channel        (cmd_demux_001_src0_channel),                                           //          .channel
		.out_ready         (mux_pipeline_001_source0_ready),                                       //   source0.ready
		.out_valid         (mux_pipeline_001_source0_valid),                                       //          .valid
		.out_startofpacket (mux_pipeline_001_source0_startofpacket),                               //          .startofpacket
		.out_endofpacket   (mux_pipeline_001_source0_endofpacket),                                 //          .endofpacket
		.out_data          (mux_pipeline_001_source0_data),                                        //          .data
		.out_channel       (mux_pipeline_001_source0_channel),                                     //          .channel
		.in_empty          (1'b0),                                                                 // (terminated)
		.out_empty         (),                                                                     // (terminated)
		.out_error         (),                                                                     // (terminated)
		.in_error          (1'b0)                                                                  // (terminated)
	);

	altera_avalon_st_pipeline_stage #(
		.SYMBOLS_PER_BEAT (1),
		.BITS_PER_SYMBOL  (153),
		.USE_PACKETS      (1),
		.USE_EMPTY        (0),
		.EMPTY_WIDTH      (0),
		.CHANNEL_WIDTH    (2),
		.PACKET_WIDTH     (2),
		.ERROR_WIDTH      (0),
		.PIPELINE_READY   (1)
	) mux_pipeline_002 (
		.clk               (sys_hps_h2f_user1_clock_clk),                             //       cr0.clk
		.reset             (hdmi_dmac_0_m_src_axi_reset_reset_bridge_in_reset_reset), // cr0_reset.reset
		.in_ready          (rsp_demux_src0_ready),                                    //     sink0.ready
		.in_valid          (rsp_demux_src0_valid),                                    //          .valid
		.in_startofpacket  (rsp_demux_src0_startofpacket),                            //          .startofpacket
		.in_endofpacket    (rsp_demux_src0_endofpacket),                              //          .endofpacket
		.in_data           (rsp_demux_src0_data),                                     //          .data
		.in_channel        (rsp_demux_src0_channel),                                  //          .channel
		.out_ready         (mux_pipeline_002_source0_ready),                          //   source0.ready
		.out_valid         (mux_pipeline_002_source0_valid),                          //          .valid
		.out_startofpacket (mux_pipeline_002_source0_startofpacket),                  //          .startofpacket
		.out_endofpacket   (mux_pipeline_002_source0_endofpacket),                    //          .endofpacket
		.out_data          (mux_pipeline_002_source0_data),                           //          .data
		.out_channel       (mux_pipeline_002_source0_channel),                        //          .channel
		.in_empty          (1'b0),                                                    // (terminated)
		.out_empty         (),                                                        // (terminated)
		.out_error         (),                                                        // (terminated)
		.in_error          (1'b0)                                                     // (terminated)
	);

	altera_avalon_st_pipeline_stage #(
		.SYMBOLS_PER_BEAT (1),
		.BITS_PER_SYMBOL  (153),
		.USE_PACKETS      (1),
		.USE_EMPTY        (0),
		.EMPTY_WIDTH      (0),
		.CHANNEL_WIDTH    (2),
		.PACKET_WIDTH     (2),
		.ERROR_WIDTH      (0),
		.PIPELINE_READY   (1)
	) mux_pipeline_003 (
		.clk               (sys_hps_h2f_user1_clock_clk),                             //       cr0.clk
		.reset             (hdmi_dmac_0_m_src_axi_reset_reset_bridge_in_reset_reset), // cr0_reset.reset
		.in_ready          (rsp_demux_src1_ready),                                    //     sink0.ready
		.in_valid          (rsp_demux_src1_valid),                                    //          .valid
		.in_startofpacket  (rsp_demux_src1_startofpacket),                            //          .startofpacket
		.in_endofpacket    (rsp_demux_src1_endofpacket),                              //          .endofpacket
		.in_data           (rsp_demux_src1_data),                                     //          .data
		.in_channel        (rsp_demux_src1_channel),                                  //          .channel
		.out_ready         (mux_pipeline_003_source0_ready),                          //   source0.ready
		.out_valid         (mux_pipeline_003_source0_valid),                          //          .valid
		.out_startofpacket (mux_pipeline_003_source0_startofpacket),                  //          .startofpacket
		.out_endofpacket   (mux_pipeline_003_source0_endofpacket),                    //          .endofpacket
		.out_data          (mux_pipeline_003_source0_data),                           //          .data
		.out_channel       (mux_pipeline_003_source0_channel),                        //          .channel
		.in_empty          (1'b0),                                                    // (terminated)
		.out_empty         (),                                                        // (terminated)
		.out_error         (),                                                        // (terminated)
		.in_error          (1'b0)                                                     // (terminated)
	);

	system_bd_mm_interconnect_2_avalon_st_adapter #(
		.inBitsPerSymbol (66),
		.inUsePackets    (0),
		.inDataWidth     (66),
		.inChannelWidth  (0),
		.inErrorWidth    (0),
		.inUseEmptyPort  (0),
		.inUseValid      (1),
		.inUseReady      (1),
		.inReadyLatency  (0),
		.outDataWidth    (66),
		.outChannelWidth (0),
		.outErrorWidth   (1),
		.outUseEmptyPort (0),
		.outUseValid     (1),
		.outUseReady     (1),
		.outReadyLatency (0)
	) avalon_st_adapter (
		.in_clk_0_clk   (sys_hps_h2f_user1_clock_clk),                                          // in_clk_0.clk
		.in_rst_0_reset (sys_hps_f2h_sdram0_data_translator_reset_reset_bridge_in_reset_reset), // in_rst_0.reset
		.in_0_data      (sys_hps_f2h_sdram0_data_agent_rdata_fifo_out_data),                    //     in_0.data
		.in_0_valid     (sys_hps_f2h_sdram0_data_agent_rdata_fifo_out_valid),                   //         .valid
		.in_0_ready     (sys_hps_f2h_sdram0_data_agent_rdata_fifo_out_ready),                   //         .ready
		.out_0_data     (avalon_st_adapter_out_0_data),                                         //    out_0.data
		.out_0_valid    (avalon_st_adapter_out_0_valid),                                        //         .valid
		.out_0_ready    (avalon_st_adapter_out_0_ready),                                        //         .ready
		.out_0_error    (avalon_st_adapter_out_0_error)                                         //         .error
	);

endmodule
