	system_bd u0 (
		.button_pio_external_connection_export       (<connected-to-button_pio_external_connection_export>),       //  button_pio_external_connection.export
		.dipsw_pio_external_connection_export        (<connected-to-dipsw_pio_external_connection_export>),        //   dipsw_pio_external_connection.export
		.hdmi_out_h_clk                              (<connected-to-hdmi_out_h_clk>),                              //                        hdmi_out.h_clk
		.hdmi_out_h16_hsync                          (<connected-to-hdmi_out_h16_hsync>),                          //                                .h16_hsync
		.hdmi_out_h16_vsync                          (<connected-to-hdmi_out_h16_vsync>),                          //                                .h16_vsync
		.hdmi_out_h16_data_e                         (<connected-to-hdmi_out_h16_data_e>),                         //                                .h16_data_e
		.hdmi_out_h16_data                           (<connected-to-hdmi_out_h16_data>),                           //                                .h16_data
		.hdmi_out_h16_es_data                        (<connected-to-hdmi_out_h16_es_data>),                        //                                .h16_es_data
		.hdmi_out_h24_hsync                          (<connected-to-hdmi_out_h24_hsync>),                          //                                .h24_hsync
		.hdmi_out_h24_vsync                          (<connected-to-hdmi_out_h24_vsync>),                          //                                .h24_vsync
		.hdmi_out_h24_data_e                         (<connected-to-hdmi_out_h24_data_e>),                         //                                .h24_data_e
		.hdmi_out_h24_data                           (<connected-to-hdmi_out_h24_data>),                           //                                .h24_data
		.hdmi_out_h36_hsync                          (<connected-to-hdmi_out_h36_hsync>),                          //                                .h36_hsync
		.hdmi_out_h36_vsync                          (<connected-to-hdmi_out_h36_vsync>),                          //                                .h36_vsync
		.hdmi_out_h36_data_e                         (<connected-to-hdmi_out_h36_data_e>),                         //                                .h36_data_e
		.hdmi_out_h36_data                           (<connected-to-hdmi_out_h36_data>),                           //                                .h36_data
		.led_pio_external_connection_export          (<connected-to-led_pio_external_connection_export>),          //     led_pio_external_connection.export
		.spi_engine_execution_0_spi_out_three_wire   (<connected-to-spi_engine_execution_0_spi_out_three_wire>),   //  spi_engine_execution_0_spi_out.three_wire
		.spi_engine_execution_0_spi_out_sdo_t        (<connected-to-spi_engine_execution_0_spi_out_sdo_t>),        //                                .sdo_t
		.spi_engine_execution_0_spi_out_sdo          (<connected-to-spi_engine_execution_0_spi_out_sdo>),          //                                .sdo
		.spi_engine_execution_0_spi_out_sdi          (<connected-to-spi_engine_execution_0_spi_out_sdi>),          //                                .sdi
		.spi_engine_execution_0_spi_out_cs           (<connected-to-spi_engine_execution_0_spi_out_cs>),           //                                .cs
		.spi_engine_execution_0_spi_out_sclk         (<connected-to-spi_engine_execution_0_spi_out_sclk>),         //                                .sclk
		.sys_clk_clk                                 (<connected-to-sys_clk_clk>),                                 //                         sys_clk.clk
		.sys_hps_h2f_reset_reset_n                   (<connected-to-sys_hps_h2f_reset_reset_n>),                   //               sys_hps_h2f_reset.reset_n
		.sys_hps_hps_io_hps_io_emac1_inst_TX_CLK     (<connected-to-sys_hps_hps_io_hps_io_emac1_inst_TX_CLK>),     //                  sys_hps_hps_io.hps_io_emac1_inst_TX_CLK
		.sys_hps_hps_io_hps_io_emac1_inst_TXD0       (<connected-to-sys_hps_hps_io_hps_io_emac1_inst_TXD0>),       //                                .hps_io_emac1_inst_TXD0
		.sys_hps_hps_io_hps_io_emac1_inst_TXD1       (<connected-to-sys_hps_hps_io_hps_io_emac1_inst_TXD1>),       //                                .hps_io_emac1_inst_TXD1
		.sys_hps_hps_io_hps_io_emac1_inst_TXD2       (<connected-to-sys_hps_hps_io_hps_io_emac1_inst_TXD2>),       //                                .hps_io_emac1_inst_TXD2
		.sys_hps_hps_io_hps_io_emac1_inst_TXD3       (<connected-to-sys_hps_hps_io_hps_io_emac1_inst_TXD3>),       //                                .hps_io_emac1_inst_TXD3
		.sys_hps_hps_io_hps_io_emac1_inst_RXD0       (<connected-to-sys_hps_hps_io_hps_io_emac1_inst_RXD0>),       //                                .hps_io_emac1_inst_RXD0
		.sys_hps_hps_io_hps_io_emac1_inst_MDIO       (<connected-to-sys_hps_hps_io_hps_io_emac1_inst_MDIO>),       //                                .hps_io_emac1_inst_MDIO
		.sys_hps_hps_io_hps_io_emac1_inst_MDC        (<connected-to-sys_hps_hps_io_hps_io_emac1_inst_MDC>),        //                                .hps_io_emac1_inst_MDC
		.sys_hps_hps_io_hps_io_emac1_inst_RX_CTL     (<connected-to-sys_hps_hps_io_hps_io_emac1_inst_RX_CTL>),     //                                .hps_io_emac1_inst_RX_CTL
		.sys_hps_hps_io_hps_io_emac1_inst_TX_CTL     (<connected-to-sys_hps_hps_io_hps_io_emac1_inst_TX_CTL>),     //                                .hps_io_emac1_inst_TX_CTL
		.sys_hps_hps_io_hps_io_emac1_inst_RX_CLK     (<connected-to-sys_hps_hps_io_hps_io_emac1_inst_RX_CLK>),     //                                .hps_io_emac1_inst_RX_CLK
		.sys_hps_hps_io_hps_io_emac1_inst_RXD1       (<connected-to-sys_hps_hps_io_hps_io_emac1_inst_RXD1>),       //                                .hps_io_emac1_inst_RXD1
		.sys_hps_hps_io_hps_io_emac1_inst_RXD2       (<connected-to-sys_hps_hps_io_hps_io_emac1_inst_RXD2>),       //                                .hps_io_emac1_inst_RXD2
		.sys_hps_hps_io_hps_io_emac1_inst_RXD3       (<connected-to-sys_hps_hps_io_hps_io_emac1_inst_RXD3>),       //                                .hps_io_emac1_inst_RXD3
		.sys_hps_hps_io_hps_io_qspi_inst_IO0         (<connected-to-sys_hps_hps_io_hps_io_qspi_inst_IO0>),         //                                .hps_io_qspi_inst_IO0
		.sys_hps_hps_io_hps_io_qspi_inst_IO1         (<connected-to-sys_hps_hps_io_hps_io_qspi_inst_IO1>),         //                                .hps_io_qspi_inst_IO1
		.sys_hps_hps_io_hps_io_qspi_inst_IO2         (<connected-to-sys_hps_hps_io_hps_io_qspi_inst_IO2>),         //                                .hps_io_qspi_inst_IO2
		.sys_hps_hps_io_hps_io_qspi_inst_IO3         (<connected-to-sys_hps_hps_io_hps_io_qspi_inst_IO3>),         //                                .hps_io_qspi_inst_IO3
		.sys_hps_hps_io_hps_io_qspi_inst_SS0         (<connected-to-sys_hps_hps_io_hps_io_qspi_inst_SS0>),         //                                .hps_io_qspi_inst_SS0
		.sys_hps_hps_io_hps_io_qspi_inst_CLK         (<connected-to-sys_hps_hps_io_hps_io_qspi_inst_CLK>),         //                                .hps_io_qspi_inst_CLK
		.sys_hps_hps_io_hps_io_sdio_inst_CMD         (<connected-to-sys_hps_hps_io_hps_io_sdio_inst_CMD>),         //                                .hps_io_sdio_inst_CMD
		.sys_hps_hps_io_hps_io_sdio_inst_D0          (<connected-to-sys_hps_hps_io_hps_io_sdio_inst_D0>),          //                                .hps_io_sdio_inst_D0
		.sys_hps_hps_io_hps_io_sdio_inst_D1          (<connected-to-sys_hps_hps_io_hps_io_sdio_inst_D1>),          //                                .hps_io_sdio_inst_D1
		.sys_hps_hps_io_hps_io_sdio_inst_CLK         (<connected-to-sys_hps_hps_io_hps_io_sdio_inst_CLK>),         //                                .hps_io_sdio_inst_CLK
		.sys_hps_hps_io_hps_io_sdio_inst_D2          (<connected-to-sys_hps_hps_io_hps_io_sdio_inst_D2>),          //                                .hps_io_sdio_inst_D2
		.sys_hps_hps_io_hps_io_sdio_inst_D3          (<connected-to-sys_hps_hps_io_hps_io_sdio_inst_D3>),          //                                .hps_io_sdio_inst_D3
		.sys_hps_hps_io_hps_io_usb1_inst_D0          (<connected-to-sys_hps_hps_io_hps_io_usb1_inst_D0>),          //                                .hps_io_usb1_inst_D0
		.sys_hps_hps_io_hps_io_usb1_inst_D1          (<connected-to-sys_hps_hps_io_hps_io_usb1_inst_D1>),          //                                .hps_io_usb1_inst_D1
		.sys_hps_hps_io_hps_io_usb1_inst_D2          (<connected-to-sys_hps_hps_io_hps_io_usb1_inst_D2>),          //                                .hps_io_usb1_inst_D2
		.sys_hps_hps_io_hps_io_usb1_inst_D3          (<connected-to-sys_hps_hps_io_hps_io_usb1_inst_D3>),          //                                .hps_io_usb1_inst_D3
		.sys_hps_hps_io_hps_io_usb1_inst_D4          (<connected-to-sys_hps_hps_io_hps_io_usb1_inst_D4>),          //                                .hps_io_usb1_inst_D4
		.sys_hps_hps_io_hps_io_usb1_inst_D5          (<connected-to-sys_hps_hps_io_hps_io_usb1_inst_D5>),          //                                .hps_io_usb1_inst_D5
		.sys_hps_hps_io_hps_io_usb1_inst_D6          (<connected-to-sys_hps_hps_io_hps_io_usb1_inst_D6>),          //                                .hps_io_usb1_inst_D6
		.sys_hps_hps_io_hps_io_usb1_inst_D7          (<connected-to-sys_hps_hps_io_hps_io_usb1_inst_D7>),          //                                .hps_io_usb1_inst_D7
		.sys_hps_hps_io_hps_io_usb1_inst_CLK         (<connected-to-sys_hps_hps_io_hps_io_usb1_inst_CLK>),         //                                .hps_io_usb1_inst_CLK
		.sys_hps_hps_io_hps_io_usb1_inst_STP         (<connected-to-sys_hps_hps_io_hps_io_usb1_inst_STP>),         //                                .hps_io_usb1_inst_STP
		.sys_hps_hps_io_hps_io_usb1_inst_DIR         (<connected-to-sys_hps_hps_io_hps_io_usb1_inst_DIR>),         //                                .hps_io_usb1_inst_DIR
		.sys_hps_hps_io_hps_io_usb1_inst_NXT         (<connected-to-sys_hps_hps_io_hps_io_usb1_inst_NXT>),         //                                .hps_io_usb1_inst_NXT
		.sys_hps_hps_io_hps_io_uart0_inst_RX         (<connected-to-sys_hps_hps_io_hps_io_uart0_inst_RX>),         //                                .hps_io_uart0_inst_RX
		.sys_hps_hps_io_hps_io_uart0_inst_TX         (<connected-to-sys_hps_hps_io_hps_io_uart0_inst_TX>),         //                                .hps_io_uart0_inst_TX
		.sys_hps_hps_io_hps_io_i2c0_inst_SDA         (<connected-to-sys_hps_hps_io_hps_io_i2c0_inst_SDA>),         //                                .hps_io_i2c0_inst_SDA
		.sys_hps_hps_io_hps_io_i2c0_inst_SCL         (<connected-to-sys_hps_hps_io_hps_io_i2c0_inst_SCL>),         //                                .hps_io_i2c0_inst_SCL
		.sys_hps_hps_io_hps_io_i2c1_inst_SDA         (<connected-to-sys_hps_hps_io_hps_io_i2c1_inst_SDA>),         //                                .hps_io_i2c1_inst_SDA
		.sys_hps_hps_io_hps_io_i2c1_inst_SCL         (<connected-to-sys_hps_hps_io_hps_io_i2c1_inst_SCL>),         //                                .hps_io_i2c1_inst_SCL
		.sys_hps_hps_io_hps_io_gpio_inst_GPIO00      (<connected-to-sys_hps_hps_io_hps_io_gpio_inst_GPIO00>),      //                                .hps_io_gpio_inst_GPIO00
		.sys_hps_hps_io_hps_io_gpio_inst_GPIO09      (<connected-to-sys_hps_hps_io_hps_io_gpio_inst_GPIO09>),      //                                .hps_io_gpio_inst_GPIO09
		.sys_hps_hps_io_hps_io_gpio_inst_GPIO35      (<connected-to-sys_hps_hps_io_hps_io_gpio_inst_GPIO35>),      //                                .hps_io_gpio_inst_GPIO35
		.sys_hps_hps_io_hps_io_gpio_inst_GPIO40      (<connected-to-sys_hps_hps_io_hps_io_gpio_inst_GPIO40>),      //                                .hps_io_gpio_inst_GPIO40
		.sys_hps_hps_io_hps_io_gpio_inst_GPIO41      (<connected-to-sys_hps_hps_io_hps_io_gpio_inst_GPIO41>),      //                                .hps_io_gpio_inst_GPIO41
		.sys_hps_hps_io_hps_io_gpio_inst_GPIO42      (<connected-to-sys_hps_hps_io_hps_io_gpio_inst_GPIO42>),      //                                .hps_io_gpio_inst_GPIO42
		.sys_hps_hps_io_hps_io_gpio_inst_GPIO43      (<connected-to-sys_hps_hps_io_hps_io_gpio_inst_GPIO43>),      //                                .hps_io_gpio_inst_GPIO43
		.sys_hps_hps_io_hps_io_gpio_inst_GPIO44      (<connected-to-sys_hps_hps_io_hps_io_gpio_inst_GPIO44>),      //                                .hps_io_gpio_inst_GPIO44
		.sys_hps_hps_io_hps_io_gpio_inst_GPIO48      (<connected-to-sys_hps_hps_io_hps_io_gpio_inst_GPIO48>),      //                                .hps_io_gpio_inst_GPIO48
		.sys_hps_hps_io_hps_io_gpio_inst_GPIO53      (<connected-to-sys_hps_hps_io_hps_io_gpio_inst_GPIO53>),      //                                .hps_io_gpio_inst_GPIO53
		.sys_hps_hps_io_hps_io_gpio_inst_GPIO54      (<connected-to-sys_hps_hps_io_hps_io_gpio_inst_GPIO54>),      //                                .hps_io_gpio_inst_GPIO54
		.sys_hps_hps_io_hps_io_gpio_inst_GPIO55      (<connected-to-sys_hps_hps_io_hps_io_gpio_inst_GPIO55>),      //                                .hps_io_gpio_inst_GPIO55
		.sys_hps_hps_io_hps_io_gpio_inst_GPIO56      (<connected-to-sys_hps_hps_io_hps_io_gpio_inst_GPIO56>),      //                                .hps_io_gpio_inst_GPIO56
		.sys_hps_hps_io_hps_io_gpio_inst_GPIO57      (<connected-to-sys_hps_hps_io_hps_io_gpio_inst_GPIO57>),      //                                .hps_io_gpio_inst_GPIO57
		.sys_hps_hps_io_hps_io_gpio_inst_GPIO58      (<connected-to-sys_hps_hps_io_hps_io_gpio_inst_GPIO58>),      //                                .hps_io_gpio_inst_GPIO58
		.sys_hps_hps_io_hps_io_gpio_inst_GPIO59      (<connected-to-sys_hps_hps_io_hps_io_gpio_inst_GPIO59>),      //                                .hps_io_gpio_inst_GPIO59
		.sys_hps_hps_io_hps_io_gpio_inst_GPIO61      (<connected-to-sys_hps_hps_io_hps_io_gpio_inst_GPIO61>),      //                                .hps_io_gpio_inst_GPIO61
		.sys_hps_hps_io_hps_io_gpio_inst_GPIO65      (<connected-to-sys_hps_hps_io_hps_io_gpio_inst_GPIO65>),      //                                .hps_io_gpio_inst_GPIO65
		.sys_hps_memory_mem_a                        (<connected-to-sys_hps_memory_mem_a>),                        //                  sys_hps_memory.mem_a
		.sys_hps_memory_mem_ba                       (<connected-to-sys_hps_memory_mem_ba>),                       //                                .mem_ba
		.sys_hps_memory_mem_ck                       (<connected-to-sys_hps_memory_mem_ck>),                       //                                .mem_ck
		.sys_hps_memory_mem_ck_n                     (<connected-to-sys_hps_memory_mem_ck_n>),                     //                                .mem_ck_n
		.sys_hps_memory_mem_cke                      (<connected-to-sys_hps_memory_mem_cke>),                      //                                .mem_cke
		.sys_hps_memory_mem_cs_n                     (<connected-to-sys_hps_memory_mem_cs_n>),                     //                                .mem_cs_n
		.sys_hps_memory_mem_ras_n                    (<connected-to-sys_hps_memory_mem_ras_n>),                    //                                .mem_ras_n
		.sys_hps_memory_mem_cas_n                    (<connected-to-sys_hps_memory_mem_cas_n>),                    //                                .mem_cas_n
		.sys_hps_memory_mem_we_n                     (<connected-to-sys_hps_memory_mem_we_n>),                     //                                .mem_we_n
		.sys_hps_memory_mem_reset_n                  (<connected-to-sys_hps_memory_mem_reset_n>),                  //                                .mem_reset_n
		.sys_hps_memory_mem_dq                       (<connected-to-sys_hps_memory_mem_dq>),                       //                                .mem_dq
		.sys_hps_memory_mem_dqs                      (<connected-to-sys_hps_memory_mem_dqs>),                      //                                .mem_dqs
		.sys_hps_memory_mem_dqs_n                    (<connected-to-sys_hps_memory_mem_dqs_n>),                    //                                .mem_dqs_n
		.sys_hps_memory_mem_odt                      (<connected-to-sys_hps_memory_mem_odt>),                      //                                .mem_odt
		.sys_hps_memory_mem_dm                       (<connected-to-sys_hps_memory_mem_dm>),                       //                                .mem_dm
		.sys_hps_memory_oct_rzqin                    (<connected-to-sys_hps_memory_oct_rzqin>),                    //                                .oct_rzqin
		.sys_rst_reset_n                             (<connected-to-sys_rst_reset_n>),                             //                         sys_rst.reset_n
		.trigger_gen_0_load_config_load_config       (<connected-to-trigger_gen_0_load_config_load_config>),       //       trigger_gen_0_load_config.load_config
		.trigger_gen_0_pulse_period_pulse_period     (<connected-to-trigger_gen_0_pulse_period_pulse_period>),     //      trigger_gen_0_pulse_period.pulse_period
		.trigger_gen_0_pulse_width_pulse_width       (<connected-to-trigger_gen_0_pulse_width_pulse_width>),       //       trigger_gen_0_pulse_width.pulse_width
		.upscale_converter_0_dfmt_enable_dfmt_enable (<connected-to-upscale_converter_0_dfmt_enable_dfmt_enable>), // upscale_converter_0_dfmt_enable.dfmt_enable
		.upscale_converter_0_dfmt_se_dfmt_se         (<connected-to-upscale_converter_0_dfmt_se_dfmt_se>),         //     upscale_converter_0_dfmt_se.dfmt_se
		.upscale_converter_0_dfmt_type_dfmt_type     (<connected-to-upscale_converter_0_dfmt_type_dfmt_type>)      //   upscale_converter_0_dfmt_type.dfmt_type
	);

