// input_buf.v

// Generated using ACDS version 20.1 720

`timescale 1 ps / 1 ps
module input_buf (
		output wire [0:0] dout,     //     dout.export
		input  wire [0:0] pad_in,   //   pad_in.export
		input  wire [0:0] pad_in_b  // pad_in_b.export
	);

	input_buf_altera_gpio_201_7hw2yni gpio_0 (
		.dout     (dout),     //     dout.export
		.pad_in   (pad_in),   //   pad_in.export
		.pad_in_b (pad_in_b)  // pad_in_b.export
	);

endmodule
