module emif_ph2_1_emif_ph2_cal_arch_fp_210_bd6u3ly #(
   parameter NUM_CALBUS_PERIPHS                                 = 0,
   parameter NUM_CALBUS_PLLS                                    = 0,
   parameter PORT_M_AXIL_ENABLE                                 = 0,
   parameter PORT_AXIL_ADDRESS_WIDTH                            = 0
) (
   output logic [1341:0]   periph_calbus_0,
   input  logic [1314:0]   periph_calbus_readdata_0,
   input  logic [32767:0]  periph_calbus_param_table_0,
   output logic [1341:0]   periph_calbus_1,
   input  logic [1314:0]   periph_calbus_readdata_1,
   input  logic [32767:0]  periph_calbus_param_table_1,
   output logic [57:0]     pll_calbus_0,
   input  logic [31:0]     pll_calbus_readdata_0,
   output logic [57:0]     pll_calbus_1,
   input  logic [31:0]     pll_calbus_readdata_1,
   output logic [57:0]     pll_calbus_2,
   input  logic [31:0]     pll_calbus_readdata_2,
   input  logic            s0_axil_clk,
   input  logic            s0_axil_rst_n,
   input  logic [26:0]     s0_axil_awaddr,
   input  logic            s0_axil_awvalid,
   output logic            s0_axil_awready,
   input  logic [31:0]     s0_axil_wdata,
   input  logic [3:0]      s0_axil_wstrb,
   input  logic            s0_axil_wvalid,
   output logic            s0_axil_wready,
   output logic [1:0]      s0_axil_bresp,
   output logic            s0_axil_bvalid,
   input  logic            s0_axil_bready,
   input  logic [26:0]     s0_axil_araddr,
   input  logic            s0_axil_arvalid,
   output logic            s0_axil_arready,
   output logic [31:0]     s0_axil_rdata,
   output logic [1:0]      s0_axil_rresp,
   output logic            s0_axil_rvalid,
   input  logic            s0_axil_rready,
   input  logic [2:0]      s0_axil_awprot,
   input  logic [2:0]      s0_axil_arprot,
   output logic [26:0]     m0_axil_awaddr,
   output logic            m0_axil_awvalid,
   input  logic            m0_axil_awready,
   output logic [31:0]     m0_axil_wdata,
   output logic [3:0]      m0_axil_wstrb,
   output logic            m0_axil_wvalid,
   input  logic            m0_axil_wready,
   input  logic [1:0]      m0_axil_bresp,
   input  logic            m0_axil_bvalid,
   output logic            m0_axil_bready,
   output logic [26:0]     m0_axil_araddr,
   output logic            m0_axil_arvalid,
   input  logic            m0_axil_arready,
   input  logic [31:0]     m0_axil_rdata,
   input  logic [1:0]      m0_axil_rresp,
   input  logic            m0_axil_rvalid,
   output logic            m0_axil_rready,
   output logic [2:0]      m0_axil_awprot,
   output logic [2:0]      m0_axil_arprot,
   output logic            s0_noc_axil_clk,
   output logic            s0_noc_axil_rst_n,
   input  logic [26:0]     s0_noc_axil_awaddr,
   input  logic            s0_noc_axil_awvalid,
   output logic            s0_noc_axil_awready,
   input  logic [31:0]     s0_noc_axil_wdata,
   input  logic [3:0]      s0_noc_axil_wstrb,
   input  logic            s0_noc_axil_wvalid,
   output logic            s0_noc_axil_wready,
   output logic [1:0]      s0_noc_axil_bresp,
   output logic            s0_noc_axil_bvalid,
   input  logic            s0_noc_axil_bready,
   input  logic [26:0]     s0_noc_axil_araddr,
   input  logic            s0_noc_axil_arvalid,
   output logic            s0_noc_axil_arready,
   output logic [31:0]     s0_noc_axil_rdata,
   output logic [1:0]      s0_noc_axil_rresp,
   output logic            s0_noc_axil_rvalid,
   input  logic            s0_noc_axil_rready,
   input  logic [2:0]      s0_noc_axil_awprot,
   input  logic [2:0]      s0_noc_axil_arprot,
   input  logic            tniul_rst_n,
   input  logic [7:0]      ls_to_cal,
   output logic [7:0]      ls_from_cal,
   input  logic            fbr_c2f_rst_n
);
   timeunit 1ns;
   timeprecision 1ps;

   emif_ph2_1_emif_ph2_cal_arch_fp_210_bd6u3ly_cal_arch_fp_top # (
      .NUM_CALBUS_PERIPHS (NUM_CALBUS_PERIPHS),
      .NUM_CALBUS_PLLS (NUM_CALBUS_PLLS),
      .PORT_M_AXIL_ENABLE (PORT_M_AXIL_ENABLE),
      .PORT_AXIL_ADDRESS_WIDTH (PORT_AXIL_ADDRESS_WIDTH)
   ) emif_ph2_1_emif_ph2_cal_arch_fp_210_bd6u3ly_cal_arch_fp_inst (
      .periph_calbus_0 (periph_calbus_0),
      .periph_calbus_readdata_0 (periph_calbus_readdata_0),
      .periph_calbus_param_table_0 (periph_calbus_param_table_0),
      .periph_calbus_1 (periph_calbus_1),
      .periph_calbus_readdata_1 (periph_calbus_readdata_1),
      .periph_calbus_param_table_1 (periph_calbus_param_table_1),
      .pll_calbus_0 (pll_calbus_0),
      .pll_calbus_readdata_0 (pll_calbus_readdata_0),
      .pll_calbus_1 (pll_calbus_1),
      .pll_calbus_readdata_1 (pll_calbus_readdata_1),
      .pll_calbus_2 (pll_calbus_2),
      .pll_calbus_readdata_2 (pll_calbus_readdata_2),
      .s0_axil_clk (s0_axil_clk),
      .s0_axil_rst_n (s0_axil_rst_n),
      .s0_axil_awaddr (s0_axil_awaddr),
      .s0_axil_awvalid (s0_axil_awvalid),
      .s0_axil_awready (s0_axil_awready),
      .s0_axil_wdata (s0_axil_wdata),
      .s0_axil_wstrb (s0_axil_wstrb),
      .s0_axil_wvalid (s0_axil_wvalid),
      .s0_axil_wready (s0_axil_wready),
      .s0_axil_bresp (s0_axil_bresp),
      .s0_axil_bvalid (s0_axil_bvalid),
      .s0_axil_bready (s0_axil_bready),
      .s0_axil_araddr (s0_axil_araddr),
      .s0_axil_arvalid (s0_axil_arvalid),
      .s0_axil_arready (s0_axil_arready),
      .s0_axil_rdata (s0_axil_rdata),
      .s0_axil_rresp (s0_axil_rresp),
      .s0_axil_rvalid (s0_axil_rvalid),
      .s0_axil_rready (s0_axil_rready),
      .s0_axil_awprot (s0_axil_awprot),
      .s0_axil_arprot (s0_axil_arprot),
      .m0_axil_awaddr (m0_axil_awaddr),
      .m0_axil_awvalid (m0_axil_awvalid),
      .m0_axil_awready (m0_axil_awready),
      .m0_axil_wdata (m0_axil_wdata),
      .m0_axil_wstrb (m0_axil_wstrb),
      .m0_axil_wvalid (m0_axil_wvalid),
      .m0_axil_wready (m0_axil_wready),
      .m0_axil_bresp (m0_axil_bresp),
      .m0_axil_bvalid (m0_axil_bvalid),
      .m0_axil_bready (m0_axil_bready),
      .m0_axil_araddr (m0_axil_araddr),
      .m0_axil_arvalid (m0_axil_arvalid),
      .m0_axil_arready (m0_axil_arready),
      .m0_axil_rdata (m0_axil_rdata),
      .m0_axil_rresp (m0_axil_rresp),
      .m0_axil_rvalid (m0_axil_rvalid),
      .m0_axil_rready (m0_axil_rready),
      .m0_axil_awprot (m0_axil_awprot),
      .m0_axil_arprot (m0_axil_arprot),
      .s0_noc_axil_clk (s0_noc_axil_clk),
      .s0_noc_axil_rst_n (s0_noc_axil_rst_n),
      .s0_noc_axil_awaddr (s0_noc_axil_awaddr),
      .s0_noc_axil_awvalid (s0_noc_axil_awvalid),
      .s0_noc_axil_awready (s0_noc_axil_awready),
      .s0_noc_axil_wdata (s0_noc_axil_wdata),
      .s0_noc_axil_wstrb (s0_noc_axil_wstrb),
      .s0_noc_axil_wvalid (s0_noc_axil_wvalid),
      .s0_noc_axil_wready (s0_noc_axil_wready),
      .s0_noc_axil_bresp (s0_noc_axil_bresp),
      .s0_noc_axil_bvalid (s0_noc_axil_bvalid),
      .s0_noc_axil_bready (s0_noc_axil_bready),
      .s0_noc_axil_araddr (s0_noc_axil_araddr),
      .s0_noc_axil_arvalid (s0_noc_axil_arvalid),
      .s0_noc_axil_arready (s0_noc_axil_arready),
      .s0_noc_axil_rdata (s0_noc_axil_rdata),
      .s0_noc_axil_rresp (s0_noc_axil_rresp),
      .s0_noc_axil_rvalid (s0_noc_axil_rvalid),
      .s0_noc_axil_rready (s0_noc_axil_rready),
      .s0_noc_axil_awprot (s0_noc_axil_awprot),
      .s0_noc_axil_arprot (s0_noc_axil_arprot),
      .tniul_rst_n (tniul_rst_n),
      .ls_to_cal (ls_to_cal),
      .ls_from_cal (ls_from_cal),
      .fbr_c2f_rst_n (fbr_c2f_rst_n)
   );
endmodule
