config lvds_rx_altera_lvds_201_tkox7hy_cfg;
		design lvds_rx_altera_lvds_201_tkox7hy;
		instance lvds_rx_altera_lvds_201_tkox7hy.core use lvds_rx_altera_lvds_core20_201.lvds_rx_altera_lvds_core20_201_bzylizq;
endconfig

