// ghrd_hps_system_iopll_0.v

// Generated using ACDS version 23.2.1 194

`timescale 1 ps / 1 ps
module ghrd_hps_system_iopll_0 (
		input  wire  refclk,   //  refclk.clk
		input  wire  rst,      //   reset.reset
		output wire  outclk_0  // outclk0.clk
	);

	ghrd_hps_system_iopll_0_altera_iopll_1931_iab6usa iopll_0 (
		.refclk   (refclk),   //   input,  width = 1,  refclk.clk
		.rst      (rst),      //   input,  width = 1,   reset.reset
		.outclk_0 (outclk_0)  //  output,  width = 1, outclk0.clk
	);

endmodule
