// clk2.v

// Generated using ACDS version 20.1 720

`timescale 1 ps / 1 ps
module clk2 (
		output wire  outclk_0, // outclk0.clk
		output wire  outclk_1, // outclk1.clk
		input  wire  refclk,   //  refclk.clk
		input  wire  rst       //   reset.reset
	);

	clk2_altera_iopll_201_ubdrv3i iopll_0 (
		.rst      (rst),      //   reset.reset
		.refclk   (refclk),   //  refclk.clk
		.outclk_0 (outclk_0), // outclk0.clk
		.outclk_1 (outclk_1)  // outclk1.clk
	);

endmodule
