// lvds_rx.v

// Generated using ACDS version 20.1 720

`timescale 1 ps / 1 ps
module lvds_rx (
		input  wire        inclock,      //      inclock.export
		input  wire        pll_areset,   //   pll_areset.export
		output wire        pll_locked,   //   pll_locked.export
		output wire        rx_coreclock, // rx_coreclock.export
		input  wire [2:0]  rx_in,        //        rx_in.export
		output wire [23:0] rx_out        //       rx_out.export
	);

	lvds_rx_altera_lvds_201_fn6lakq lvds_0 (
		.rx_in        (rx_in),        //        rx_in.export
		.rx_out       (rx_out),       //       rx_out.export
		.rx_coreclock (rx_coreclock), // rx_coreclock.export
		.inclock      (inclock),      //      inclock.export
		.pll_areset   (pll_areset),   //   pll_areset.export
		.pll_locked   (pll_locked)    //   pll_locked.export
	);

endmodule
